// <auto-generated>
// Bu dosya Steamworks~/tools/gen_steam_achievements.py tarafindan
// Design/Progression/achievements.json (77 basarim) kaynagindan uretildi. Elle duzenlemeyin; ureteci calistirin.
// </auto-generated>
using System;
using System.Collections.Generic;

namespace Project.Platform
{
    /// <summary>
    /// Backend basarim id'leri (<c>Harekat.Domain.Catalogs.AchievementCatalog</c> = Design/Progression/achievements.json)
    /// ile Steamworks API adlari arasinda esleme. Steam Partner'da ayni API adlariyla basarim tanimlari olusturulmalidir
    /// (liste: <c>Steamworks~/achievements_partner.csv</c>).
    /// </summary>
    public static class SteamAchievementMap
    {
        /// <summary>Esleme kaynagi.</summary>
        public const string Source = "Design/Progression/achievements.json";

        /// <summary>Kaynaktaki basarim sayisi.</summary>
        public const int Count = 77;

        /// <summary>Steam API adi on eki.</summary>
        public const string ApiNamePrefix = "ACH_";

        static readonly Dictionary<string, string> BackendToSteam = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "first_blood", "ACH_FIRST_BLOOD" }, // combat: İlk Kan
            { "first_victory", "ACH_FIRST_VICTORY" }, // career: İlk Zafer
            { "sharpshooter_10", "ACH_SHARPSHOOTER_10" }, // combat: Keskin Nişancı I
            { "sharpshooter_100", "ACH_SHARPSHOOTER_100" }, // combat: Keskin Nişancı II
            { "sharpshooter_500", "ACH_SHARPSHOOTER_500" }, // combat: Keskin Nişancı III
            { "veteran_10", "ACH_VETERAN_10" }, // career: Kıdemli Asker I
            { "veteran_50", "ACH_VETERAN_50" }, // career: Kıdemli Asker II
            { "veteran_100", "ACH_VETERAN_100" }, // career: Kıdemli Asker III
            { "veteran_500", "ACH_VETERAN_500" }, // career: Kıdemli Asker IV
            { "killer_25", "ACH_KILLER_25" }, // combat: Avcı I
            { "killer_100", "ACH_KILLER_100" }, // combat: Avcı II
            { "killer_500", "ACH_KILLER_500" }, // combat: Avcı III
            { "killer_1000", "ACH_KILLER_1000" }, // combat: Avcı IV
            { "champion_5", "ACH_CHAMPION_5" }, // career: Şampiyon I
            { "champion_25", "ACH_CHAMPION_25" }, // career: Şampiyon II
            { "champion_100", "ACH_CHAMPION_100" }, // career: Şampiyon III
            { "damage_10k", "ACH_DAMAGE_10K" }, // combat: Hasar Ustası I
            { "damage_100k", "ACH_DAMAGE_100K" }, // combat: Hasar Ustası II
            { "survivor_600", "ACH_SURVIVOR_600" }, // survival: Hayatta Kalan I
            { "survivor_1200", "ACH_SURVIVOR_1200" }, // survival: Hayatta Kalan II
            { "top3_10", "ACH_TOP3_10" }, // career: Podyum
            { "command_transfer", "ACH_COMMAND_TRANSFER" }, // squad: Komuta Devri
            { "squad_builder", "ACH_SQUAD_BUILDER" }, // social: Tim Kurucu
            { "social_butterfly", "ACH_SOCIAL_BUTTERFLY" }, // social: Sosyal Asker
            { "season_grinder", "ACH_SEASON_GRINDER" }, // season: Sezon Askeri
            { "rank_onbasi", "ACH_RANK_ONBASI" }, // career: Onbaşı
            { "rank_cavus", "ACH_RANK_CAVUS" }, // career: Çavuş
            { "rank_astsubay", "ACH_RANK_ASTSUBAY" }, // career: Astsubay
            { "rank_officer", "ACH_RANK_OFFICER" }, // career: Subay
            { "rank_albay", "ACH_RANK_ALBAY" }, // career: Albay
            { "cosmetic_collector", "ACH_COSMETIC_COLLECTOR" }, // cosmetic: Koleksiyoncu
            { "bot_slayer", "ACH_BOT_SLAYER" }, // career: Bot Avcısı
            { "region_warrior", "ACH_REGION_WARRIOR" }, // career: Bölge Askeri
            { "elo_climber", "ACH_ELO_CLIMBER" }, // career: Elo Tırmanışı
            { "perfect_squad", "ACH_PERFECT_SQUAD" }, // squad: Tam Tim
            { "command_win", "ACH_COMMAND_WIN" }, // squad: Komuta Devri — Zafer
            { "sniper_300", "ACH_SNIPER_300" }, // combat: Keskin Nişancı — Uzak Mesafe
            { "artillery_master", "ACH_ARTILLERY_MASTER" }, // support: Topçu Ustası
            { "artillery_first", "ACH_ARTILLERY_FIRST" }, // support: Ateş Emri
            { "order_follow", "ACH_ORDER_FOLLOW" }, // squad: Takipteyiz
            { "order_hold", "ACH_ORDER_HOLD" }, // squad: Mevzilen
            { "order_attack", "ACH_ORDER_ATTACK" }, // squad: Hücum
            { "order_rally", "ACH_ORDER_RALLY" }, // squad: Toplanma
            { "medkit_savior", "ACH_MEDKIT_SAVIOR" }, // survival: Sıhhiye
            { "armor_up", "ACH_ARMOR_UP" }, // survival: Zırhlı
            { "loot_hoarder", "ACH_LOOT_HOARDER" }, // survival: Ganimetçi
            { "grenade_frag", "ACH_GRENADE_FRAG" }, // combat: Bomba Atışı
            { "smoke_screen", "ACH_SMOKE_SCREEN" }, // support: Sis Perdesi
            { "mpt76_kills", "ACH_MPT76_KILLS" }, // weapon: MPT-76 Ustası
            { "mpt55_kills", "ACH_MPT55_KILLS" }, // weapon: MPT-55 Ustası
            { "g3_kills", "ACH_G3_KILLS" }, // weapon: G3A7 Ustası
            { "knt76_kills", "ACH_KNT76_KILLS" }, // weapon: KNT-76 Ustası
            { "jng90_kills", "ACH_JNG90_KILLS" }, // weapon: Bora-12 Ustası
            { "pmt76_kills", "ACH_PMT76_KILLS" }, // weapon: PMT-76 Ustası
            { "sar109_kills", "ACH_SAR109_KILLS" }, // weapon: SAR 109T Ustası
            { "escort_kills", "ACH_ESCORT_KILLS" }, // weapon: Escort Ustası
            { "pistol_kills", "ACH_PISTOL_KILLS" }, // weapon: Tabanca Ustası
            { "kirpi_driver", "ACH_KIRPI_DRIVER" }, // vehicle: Kirpi Sürücüsü
            { "heli_passenger", "ACH_HELI_PASSENGER" }, // vehicle: Hava İntikal
            { "zone_edge", "ACH_ZONE_EDGE" }, // survival: Çemberde Dur
            { "final_circle", "ACH_FINAL_CIRCLE" }, // survival: Son Çember
            { "reload_under_fire", "ACH_RELOAD_UNDER_FIRE" }, // combat: Ateş Altında Şarjör
            { "no_death_win", "ACH_NO_DEATH_WIN" }, // career: Yarasız Zafer
            { "squad_wipe", "ACH_SQUAD_WIPE" }, // combat: Tim Temizliği
            { "assist_king", "ACH_ASSIST_KING" }, // combat: Destek Ateşi
            { "damage_1m", "ACH_DAMAGE_1M" }, // combat: Hasar Ustası III
            { "season_xp_25k", "ACH_SEASON_XP_25K" }, // season: Sezon Gazisi
            { "cosmetics_15", "ACH_COSMETICS_15" }, // cosmetic: Teçhizat Koleksiyoncusu
            { "friends_20", "ACH_FRIENDS_20" }, // social: Birlik Ruhu
            { "training_complete", "ACH_TRAINING_COMPLETE" }, // tutorial: Poligon Mezunu
            { "first_order", "ACH_FIRST_ORDER" }, // squad: İlk Emir
            { "multi_kill_3", "ACH_MULTI_KILL_3" }, // combat: Üçlü Vuruş
            { "night_ops", "ACH_NIGHT_OPS" }, // career: Gece Harekâtı
            { "map_ayaz", "ACH_MAP_AYAZ" }, // career: Ayaz Geçidi Gazisi
            { "map_liman", "ACH_MAP_LIMAN" }, // career: Mavi Liman Gazisi
            { "revive_ally", "ACH_REVIVE_ALLY" }, // squad: Yoldaşını Kurtar
            { "headshot_only_win", "ACH_HEADSHOT_ONLY_WIN" } // combat: Keskin Zafer
        };

        static Dictionary<string, string> _steamToBackend;

        /// <summary>Tum acik eslemeler (backend id -> Steam API adi).</summary>
        public static IReadOnlyDictionary<string, string> All => BackendToSteam;

        /// <summary>Id acik listede mi (Partner'da tanimli olmasi beklenen basarimlar).</summary>
        public static bool IsKnown(string backendAchievementId)
        {
            return !string.IsNullOrWhiteSpace(backendAchievementId) && BackendToSteam.ContainsKey(backendAchievementId);
        }

        /// <summary>Acik listede olan id icin Steam API adi.</summary>
        public static bool TryGetSteamApiName(string backendAchievementId, out string steamApiName)
        {
            return TryGetSteamApiName(backendAchievementId, false, out steamApiName);
        }

        /// <summary>
        /// Steam API adi. <paramref name="allowConvention"/> true ise listede olmayan yeni backend id'leri
        /// <see cref="ToConventionApiName"/> kuraliyla eslenir (Partner'da tanimli degilse Steam reddeder; zararsiz).
        /// </summary>
        public static bool TryGetSteamApiName(string backendAchievementId, bool allowConvention, out string steamApiName)
        {
            steamApiName = null;
            if (string.IsNullOrWhiteSpace(backendAchievementId))
                return false;

            var id = backendAchievementId.Trim();
            if (BackendToSteam.TryGetValue(id, out steamApiName))
                return true;

            if (!allowConvention)
                return false;

            steamApiName = ToConventionApiName(id);
            return steamApiName != null;
        }

        /// <summary>Steam API adindan backend id'si (yalnizca acik liste).</summary>
        public static bool TryGetBackendId(string steamApiName, out string backendId)
        {
            backendId = null;
            if (string.IsNullOrWhiteSpace(steamApiName))
                return false;

            if (_steamToBackend == null)
            {
                var reverse = new Dictionary<string, string>(StringComparer.Ordinal);
                foreach (var pair in BackendToSteam)
                    reverse[pair.Value] = pair.Key;
                _steamToBackend = reverse;
            }

            return _steamToBackend.TryGetValue(steamApiName.Trim(), out backendId);
        }

        /// <summary>Kural: <c>"ACH_" + id.ToUpperInvariant()</c>; harf/rakam disi karakterler alt cizgi olur.</summary>
        public static string ToConventionApiName(string backendAchievementId)
        {
            if (string.IsNullOrWhiteSpace(backendAchievementId))
                return null;

            var id = backendAchievementId.Trim();
            var chars = new char[id.Length];
            for (var i = 0; i < id.Length; i++)
            {
                var c = id[i];
                var ascii = c < 128 && char.IsLetterOrDigit(c);
                chars[i] = ascii ? char.ToUpperInvariant(c) : '_';
            }

            return ApiNamePrefix + new string(chars);
        }
    }
}
