export const meta = {
  name: 'harekat-aaa-g4',
  description: 'HAREKÂT AAA URP dalgası G4: özel renderer feature (contact shadow, SSR), volumetrik sis/ışık, planar yansıma, terrain height-blend+parallax+çamur, GPU mesh çim+rüzgâr, HLOD/streaming, VFX Graph köprüsü, AAA benchmark sahnesi (8 Sonnet ajanı)',
  phases: [{ title: 'G4', detail: '8 paralel ajan, yalnız yeni dosyalar' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${ROOT}/Tools/UnityVerify/out_g4_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 URP 17.6 C# at ${ROOT}. Goal: AAA-level visuals in URP (target look: Tarkov weapon feel + Sons of the Forest environment + Turkish military atmosphere). Context: ${ROOT}/Docs/GERCEKCILIK_PLANI.md §1.3 perf targets (GTX1660S/RTX3050, 1080p Medium 60 FPS).
Editor can't run here. C# is verified with ${V(id)} (0 errors in your files, tests passing). Shaders (.shader/.hlsl) CANNOT be compiled here: write them carefully against URP 17 ShaderLibrary (Packages/com.unity.render-pipelines.universal/ShaderLibrary includes, RenderGraph-era API: ScriptableRendererFeature + ScriptableRenderPass with RecordRenderGraph; also keep it compiling with our stubs — if a URP type is missing from Tools/UnityVerify stubs, add a minimal stub there, or wrap in reflection). Put shaders under ${ROOT}/Assets/_Project/Shaders/<Area>/ and load them with Shader.Find("HAREKAT/...") — if not found, log one warning and fall back to the current procedural/URP-Lit path (golden rule: nothing breaks when the shader/asset is missing).
IMPORTANT: another 15-agent wave (G3) is editing existing files right now: Rendering/PostProcessing*, RuntimeGlobalVolume, Atmosphere*, RenderSettingsUtil, MaterialLibrary/MaterialSpec/ProceduralPbr, PerformanceProfile, RenderPipelineInfo, Editor/AssetGeneration, Content/*, World/Terrain*, Tree*, Rock*, Vegetation*, Weapons/WeaponViewModel*, CameraRig, Audio/*, Vfx/*, Characters/Soldier*, Transport/*Model*, Vehicles/*ModelBuilder*, catalogs. DO NOT edit those. Create NEW files only; if wiring into an existing file is needed, expose a public static entry point (e.g. XxxSystem.Install(camera/terrain/settings tier)) and list the exact one-line hook calls needed in your concerns as "ENTEGRASYON: <file>: <call>" — the integrator will add them later.
Quality tiers: 0 Düşük,1 Orta,2 Yüksek,3 Ultra — every feature has a per-tier on/off + cost knob and is OFF or cheapest on Düşük.
No deletes, no .meta edits, no file-changing git. UnityEngine.Application inside Project.* namespaces. Turkish UI strings. Pure math in testable classes + EditMode tests (NUnit shim: no Assert.That/CollectionAssert; tests needing Infrastructure wrapped in #if UNITY_EDITOR).
Write a short section for your feature into ${ROOT}/Docs/AAA_URP_20.md under the heading "## ${id}" (create the file if missing; append only): what it does, tier costs, what Cursor must verify in Unity. Append one dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük".`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['S1-ekran-uzayi', 'Items 1,2,4: a small custom URP renderer-feature framework (Infrastructure/Rendering/Features/HarekatRendererFeatures*.cs: register/enable per tier at runtime via reflection on the active UniversalRendererData) + Screen-Space Contact Shadows (short raymarch along sun dir in depth buffer, half-res, applied to shadow/AO term) + SSR-lite (hi-Z-free linear raymarch on depth+normals for wet ground/water/glass/metal, roughness cutoff, fades to reflection probe; Yüksek/Ultra only). Shaders: Shaders/ScreenSpace/*.'],
  ['S2-volumetrik', 'Items 5,6: Volumetric fog + light shafts as a renderer feature: quarter-res raymarch in view frustum with height fog density, sun main-light shadowmap sampling (URP shadow library) for god rays, blue-noise jitter + temporal blend, bilateral upsample; parameters driven by a public VolumetricFogSettings (density, height falloff, anisotropy g, sun intensity) with presets per weather/time (Açık/Sisli/Yağmurlu, Şafak/Gündüz/Akşam/Gece). Shaders/Volumetric/*. Expose VolumetricFog.Install + ApplyPreset.'],
  ['S3-yansima', 'Items 8,9: Planar reflection for water bodies (Infrastructure/Rendering/PlanarReflection*.cs: second camera with oblique near clip plane, half/quarter res per tier, culling mask w/o small props, disabled on Düşük, max 1 active surface — nearest visible) feeding a _PlanarReflectionTex global; + ReflectionProbePlacer (new file): auto places box-projected reflection probes per settlement/building interior and one per location exterior, baked or realtime-on-demand per tier, with budget. List ENTEGRASYON hooks for WorldWater/WaterSurface and SceneBuilder.'],
  ['S4-arazi-shader', 'Items 10,11,15: Terrain height-blend shader (Shaders/Terrain/HarekatTerrainLit.shader: URP terrain-compatible 4–8 layers, height-based blending using mask map height channel, triplanar on slopes > threshold, distance-based macro variation, detail normal) + Parallax Occlusion Mapping option for ground/rock/mud materials (Shaders/Surface/HarekatParallaxLit.shader, Lit-compatible properties so MaterialLibrary can swap) + wet MUD material with puddles (wetness mask darkens albedo, raises smoothness, flattens normals; rain increases wetness globally via _HarekatWetness). Binder: Infrastructure/World/TerrainShaderBinder.cs (switches terrain materialTemplate when shader exists). Document PBR standard (albedo luminance ranges, ORM packing, texel density 512 px/m) in AAA_URP_20.md.'],
  ['S5-cim-ruzgar', 'Items 12,13: GPU-instanced MESH grass (Infrastructure/World/Grass/*: chunked 16 m cells around camera, Graphics.RenderMeshInstanced (or RenderMeshIndirect if available) with per-instance position/rotation/scale/color, frustum + distance culling, density from terrain alphamap (grass on grass layers, none on road/rock/snow), 3 blade-clump mesh variants, density/distance per tier, player/vehicle trampling via a small interactor buffer) + Wind shader (Shaders/Vegetation/HarekatVegetationWind.shader + grass shader: global _HarekatWind dir/strength/gust from weather, vertex-color R=bend weight, trunk sway + branch flutter, alpha-cutout + translucency, GPU instancing + SRP batcher compatible). Expose WindSystem.SetWeather.'],
  ['S6-hlod-akis', 'Item 19: HLOD + occlusion + streaming: Editor/HlodBuilder.cs (per settlement: combine building/prop meshes into a far-LOD mesh per material, simplified by dropping small parts, hooked as last LOD or a distance-swapped proxy) + Infrastructure/World/HlodProxy.cs runtime swap with hysteresis; occlusion culling bake helper (Editor menu "HAREKÂT/Optimizasyon/Occlusion Bake" with sensible smallestOccluder/backfaceThreshold); TextureStreamingSetup (mipmap streaming budget per tier, QualitySettings.streamingMipmaps*). Also a TerrainStreaming note in AAA_URP_20.md for future 8–10 km maps (tile split plan). Pure helpers tested.'],
  ['S7-vfx-graph', 'Item 16 (+14 integration): VFX Graph bridge: add a versionDefine HAREKAT_VFXGRAPH for com.unity.visualeffectgraph into a NEW asmdef Project.Infrastructure.VfxGraph (folder Infrastructure/VfxGraph/) referencing Project.Infrastructure; inside #if HAREKAT_VFXGRAPH a VfxGraphPlayer that pools VisualEffect instances loaded from Resources/VFX/*.vfx; outside the define a no-op. In Infrastructure (no package dependency) add IGpuVfxBackend + GpuVfx.Backend static hook so GameVfx can later prefer GPU effects. Write Docs/VFX_GRAPH_SPEC.md: exact graphs Cursor must build in the editor (muzzle flash+smoke per weapon class, bullet impact per SurfaceKind with sparks/dust/debris, explosion with fireball/shockwave/smoke column/debris, rotor dust, rain/snow GPU, smoke grenade volume), exposed property names, spawn events, budgets per tier.'],
  ['S8-benchmark-sahne', 'THE AAA BENCHMARK SCENE (most important): new scene "AAA_Benchmark" built by Editor/AaaBenchmarkSceneBuilder.cs (menu "HAREKÂT/Kurulum/AAA Benchmark Sahnesi"; ENTEGRASYON line for SetupAll) and Presentation/Benchmark/AaaBenchmarkBootstrap.cs: ~150×150 m terrain piece with mud + rock + grass zones and a small forest patch (use existing TreeFactory/RockFactory/TerrainGenerator public APIs only), 1 village house (BuildingGenerator) you can enter, 1 Kirpi (existing builder), 1 soldier bot standing guard/patrolling, player spawns with MPT-76 (reload + fire work via existing player prefab path used by TrainingBootstrap — read it), steel targets + wall for decals and VFX, day + light fog preset. Two modes: Oyna (playable) and Vitrin (scripted cinematic camera path through 6 shots: weapon close-up, soldier, Kirpi, house interior, forest, firing at targets) + screenshot key F12 to Logs/benchmark/*.png. Add main menu button "AAA TEST SAHNESİ" via MainMenuController.ExtraButtons and SceneNames constant (new file or append). Turn on every G4 feature at Ultra here via their Install hooks if the types exist (use reflection by type name so it compiles before the others land). Write Docs/CURSOR_AAA_BENCHMARK.md: the 20-item checklist with how to verify each in this scene, which free assets to bind first (ambientCG mud/rock/grass, Poly Haven HDRI, Megascans trees, Mixamo rifle anims, Sonniss gun sounds), and the rule: no rollout to big maps before owner says the scene is "gerçekten çok iyi".'],
]
phase('G4')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G4', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
