export const meta = {
  name: 'harekat-assets-g9',
  description: 'HAREKÂT G9: gerçek CC0 varlıklar (ambientCG/Poly Haven dokular+HDRI, Poly Haven 3B modeller, CC0 ses araştırma) + otomatik bağlama + otomatik ekran görüntüsü modu (4 Sonnet ajanı)',
  phases: [{ title: 'G9 Varlık', detail: '4 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g9_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 URP 17.6 C# at ${ROOT}. Goal now: replace procedural look with REAL photoscanned CC0 assets for the AAA_Benchmark scene first (mud, rock, grass, forest ground, village house, small forest; day + light fog), then Kuzgun Vadisi.
The ContentOverrides system already exists: grep Infrastructure/Content/ContentOverrides*.cs, ContentIds.cs, Editor/ContentOverridesSetup.cs and the validator — learn the slot types and TryGet* API before writing binding code. Overrides live in Assets/_Project/Resources/ContentOverrides.asset.
Network is available (curl). ONLY download assets whose license is CC0 (ambientCG, Poly Haven) or explicitly allows commercial use in games without attribution restrictions incompatible with shipping; record every asset in ${ROOT}/Assets/ThirdParty/README.md (name | source URL | license | author | date | size). Keep total download size reasonable (textures 2K, JPG for albedo/rough/AO, PNG for normal; HDRI 4K .exr or 2K if large). .gitattributes LFS rules exist — add missing extensions (exr, fbx, glb, gltf, blend not needed) if absent.
DISK GUARD: the disk recently filled up. Before every download run: df -g /System/Volumes/Data | tail -1 — if free space < 8 GB, STOP downloading and report. Total downloads must stay <= 1.5 GB (textures/HDRI agent), <= 1 GB (models), <= 0.5 GB (audio); textures/HDRI already partly downloaded in Assets/ThirdParty/Textures and HDRI by a previous interrupted run — reuse, do not re-download. Download zips into ${SCRATCH}/dl (never the repo), extract only the needed maps, then remove only the zip/temp files YOU created in ${SCRATCH}/dl.
DO NOT launch Unity (the orchestrator runs Unity batch itself; only one Unity process may use the project). Write Editor code that runs in batch mode and verify C# with ${V(id)} (0 errors, tests passing). No deletes/.meta edits/file-changing git. UnityEngine.Application inside Project.*. Append one dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük".`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['V1-dokular-hdri', `Textures + HDRI. Download from ambientCG API (https://ambientcg.com/api/v2/full_json?... and downloads zip 2K-JPG) and/or Poly Haven API (https://api.polyhaven.com/assets?t=textures, /files/<id>): wet mud, dry mud/dirt, forest ground (needles/leaves), grass+dirt mix, meadow grass ground, granite rock, limestone/cliff rock, gravel road, asphalt/dirt road, plaster wall (old, Anatolian village), stone wall (rubble masonry), clay roof tiles, rusted metal sheet, concrete, weathered wood planks, military canvas/fabric. And 4 Poly Haven HDRIs: clear day, overcast, sunrise/dawn, sunset (mountain/rural preferred) at 2K/4K.
Place under Assets/ThirdParty/Textures/<assetId>/ and Assets/ThirdParty/HDRI/.
Write Editor/ThirdParty/ThirdPartyBinder.cs (namespace Project.EditorTools): (a) AssetPostprocessor-like import fix: normal maps → TextureImporterType.NormalMap, roughness/AO/height → sRGB off; max size 2048; (b) builds URP/Lit materials per texture set (ORM: pack AO→G? follow the project's existing MaterialLibrary mask convention — grep ProceduralPbr/MaterialLibrary for how _MetallicGlossMap/_OcclusionMap are used; convert roughness→smoothness by inverting into the alpha of a packed mask texture you generate in C# at bind time); (c) creates TerrainLayer assets for ground sets; (d) writes overrides: MaterialOverride for matching MaterialId values (map each downloaded set to the best MaterialId — list mapping in a table in Docs/VARLIK_BAGLAMA.md), TerrainLayerOverride for terrain layers, SkyOverride for HDRIs (cubemap import: TextureImporterShape.TextureCube). Public static entry: ThirdPartyBinder.BindAll() returning a report string. Add to Editor/BatchEntry.cs a method BindThirdParty() that calls ThirdPartyBinder.BindAll() then, IF a type Project.EditorTools.ThirdPartyModelBinder exists, its static BindAll() via reflection (another agent writes it), then runs the ContentOverrides validator and logs the report; AssetDatabase.SaveAssets.`],
  ['V2-modeller', `3D models from Poly Haven (CC0): https://api.polyhaven.com/assets?t=models — pick rocks/boulders (4–6), cliff/rock formations if any, tree/shrub/plant models (pine/fir/conifer, deciduous, bushes, dead tree/log, grass clumps if any), village props (wooden crates, barrels, fences, wooden cart, sacks, stone well, firewood, ladders, buckets), and any rural building parts. Download FBX (or glTF if FBX missing — Unity 6000.6 does NOT import glTF natively without a package; prefer FBX; if only glTF/blend exist, skip that asset) at 1K or 2K textures. Place under Assets/ThirdParty/Models/<assetId>/.
Write Editor/ThirdParty/ThirdPartyModelBinder.cs (namespace Project.EditorTools, public static string BindAll()): set ModelImporter settings (scale so 1 unit = 1 m — check bounds after import and fix globalScale, generate colliders off, read/write off, materials: extract and convert to URP/Lit using the downloaded textures), auto-create LODGroup from *_LOD0/1/2 meshes if present, else a single-LOD prefab plus a cheap LOD (the procedural fallback stays valid), build prefabs into Assets/ThirdParty/Prefabs/, then write RockOverride / VegetationOverride (per species) / PropOverride entries into ContentOverrides.asset (grep the exact entry types and fields). Document mapping (asset → species/prop id) in Docs/VARLIK_BAGLAMA.md under a "Modeller" section (append). Check that procedural scatter (TreeScatter/RockScatter/PropFactory) actually consults these overrides — if a call site is missing, add a minimal null-safe lookup.`],
  ['V3-ses-kaynaklari', `Real weapon & ambience sounds with a shipping-safe license. Research CC0 / royalty-free-commercial sources downloadable WITHOUT login/API key: e.g. Sonniss GDC Game Audio Bundles (royalty free, commercial OK — check exact license text; bundles are multi-GB zips: do NOT download a whole bundle; check if individual files or smaller parts are available, else write exact instructions), OpenGameArt CC0 weapon sound packs, other CC0 libraries. Download only what is CC0 or clearly commercial-OK, prioritize: rifle 7.62 / 5.56 close + distant, MG bursts, 9mm pistol, bolt-action sniper, shotgun, explosions near/far, bullet whiz/crack, shell casings on concrete/dirt, reload foley (mag out/in, bolt), wind, forest birds, night insects, rain. Convert to 44.1/48 kHz mono WAV (or OGG) with ffmpeg/afconvert/sox if available, trim silence, loudness-normalize per category, and place following Docs/SES_GERCEKCILIK.md (A2 section) naming: Assets/_Project/Resources/Audio/Weapons/<weaponId>/<layer>_<n>.wav and _class/<caliber>/..., ambience under Resources/Audio/Ambience/<biome>/ (grep WeaponClipLibrary + AmbienceBeds for exact folder/layer names). If nothing shipping-safe is obtainable without login, write Docs/SES_KAYNAK_LISTESI.md with exact URLs + steps for the owner and DO NOT download questionable files. Record licenses in Assets/ThirdParty/README.md.`],
  ['V4-oto-ekran', `Auto-screenshot / automated visual QA mode so the orchestrator (who cannot see the screen) can inspect visuals from a built player. Presentation/Benchmark/* (AaaBenchmarkBootstrap, Vitrin camera path) + Presentation/Bootstrap (command-line parsing helper; grep how -benchmark is parsed): add command-line flags for the built player: "-otoekran <outDir>" → on launch go straight to AAA_Benchmark (no menu), run Vitrin mode, at each of the 6 shots wait ~2.5 s for TAA/temporal to settle then ScreenCapture to <outDir>/<nn>_<shot>.png at 1920x1080 (set Screen.SetResolution windowed 1920x1080 first), also capture one per quality tier (0..3) of shot 1 and the F3 perf numbers into <outDir>/perf.csv, then Application.Quit(). Also "-otoekran-harita <sceneName> <outDir>" → load that map scene, spawn camera at 5 predefined viewpoints (village center, forest edge, mountain overlook, road, lake) found from world metadata/settlements, capture, quit. Make it robust: timeouts, never hang (hard quit after 120 s), log "[OTOEKRAN] bitti" at the end. Write a shell script Tools/UnityVerify/oto_ekran.sh that launches Builds/macOS/HAREKAT.app/Contents/MacOS/* with the flags, waits for exit, and lists the PNGs. Add EditMode tests for the arg parser.`],
]
phase('G9 Varlık')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G9 Varlık', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
