export const meta = {
  name: 'harekat-audio-g5',
  description: 'HAREKÂT ses gerçekçiliği G5: balistik akustik (ses hızı gecikmesi, süpersonik çatlama, vadi yankısı), silah foley, diyalog sistemi v2 (stres/yön bildirimi/yakın bağırış), daha iyi Türkçe ses üretimi, ortam + HDR miks (5 Sonnet ajanı)',
  phases: [{ title: 'G5 Ses', detail: '5 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${ROOT}/Tools/UnityVerify/out_g5_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 C# at ${ROOT}. Owner wants AAA-level audio realism: gunfire like Tarkov/CoD MW (layered, distance-aware, environment-aware) and very good Turkish military dialogue. Read ${ROOT}/Docs/GERCEKCILIK_PLANI.md §2.3 (ses) only.
Editor can't run here; verify C# with ${V(id)} (0 errors in your files, tests passing).
IMPORTANT parallel work: agent C11 (G3) is editing Audio/GameAudio.cs, SoundId.cs, AudioPool.cs, AudioQuality.cs, FootstepEmitter.cs (layers, occlusion, voice cap). DO NOT edit those five files. Create NEW files under Infrastructure/Audio/<Area>/; expose static entry points and list needed one-line hooks in concerns as "ENTEGRASYON: <file>: <call>". Golden rule: missing clip/asset → procedural fallback (ProceduralAudioSynth) still works.
No deletes, no .meta edits, no file-changing git. UnityEngine.Application inside Project.* namespaces. Turkish strings. Pure logic in testable classes + EditMode tests (NUnit shim: no Assert.That/CollectionAssert; Infrastructure-dependent tests in #if UNITY_EDITOR).
Append a section "## ${id}" to ${ROOT}/Docs/SES_GERCEKCILIK.md (create if missing, append only) describing behavior + what Cursor must verify/bind in Unity. Append one dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük".`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['A1-balistik-akustik', 'Infrastructure/Audio/Acoustics/*: (1) speed-of-sound delay for distant shots/explosions (343 m/s; muzzle report arrives after the bullet), (2) supersonic bullet crack + subsonic whiz-by for near misses (closest-approach of bullet ray to listener < 6 m; crack is directional from the bullet path, not the shooter), (3) air absorption: distance-based low-pass + level curve per caliber class (pistol/rifle/MG/sniper/explosion), (4) terrain/valley echo: a few budgeted raycasts from listener toward shot direction ±, find cliffs/buildings within 40–400 m, schedule 1–3 delayed, filtered reflections ("Kuzgun Vadisi" should ring), (5) indoor slapback when shooter is inside. Pure AcousticsMath (delays, gains, cutoff Hz) with tests. Hook point: Acoustics.OnShot(origin, dir, caliber, suppressed) and Acoustics.OnBulletPassed(rayOrigin, rayDir, maxDist).'],
  ['A2-silah-foley', 'Weapon foley & per-weapon sound profiles: Application/Catalogs or Core data WeaponSoundProfile (per WeaponId: caliber class, mech set, core set, low-end thump, tail set, suppressed variant, fire-rate-aware tail cut, shell drop type) for ALL weapons in WeaponCatalog; Infrastructure/Audio/Foley/*: multi-step reload foley timed to reload phases (mag release, mag out, pouch, mag in, slap, bolt/charging handle; tactical vs empty), fire selector click, dry fire, weapon switch/holster, ADS cloth/gear rustle, sprint gear rattle + plate carrier, prone/landing body foley. Expose WeaponFoley.Play(stepId, weaponId, position). Also a clip-name convention so Cursor can drop Sonniss recordings: Resources/Audio/Weapons/<weaponId>/<layer>_<n>.wav auto-discovered (with fallback to caliber class folder, then procedural).'],
  ['A3-diyalog-v2', 'Dialogue system v2 (may edit Infrastructure/Audio/Radio*.cs files and the voice manifest loader; not the 5 forbidden files): stress states sakin/çatışma/panik chosen from combat intensity + health; proximity shouts (3D, unfiltered, loud) vs radio (filtered) — nearby squadmates shout, far ones use radio; contextual barks with variation and anti-repetition memory: "Şarjör!", "Yeniden dolduruyorum!", "El bombası!", "Yaralandım!", "Vuruldum!", "Düşman düştü!", "Bana ört!", "İlerliyorum!", "Sis atıyorum!", enemy spotted WITH clock direction + distance built from parts ("Saat üç yönü" + "yüz metre" + "düşman piyade") using a phrase concatenation system; 8 distinct soldier voice identities (voiceId → pitch/formant/speed/intensity) consistent per soldier; rank-aware replies (Er answers "Emredersiniz komutanım"); radio processing upgrade: band-pass 300–3400 Hz, soft saturation, compression, squelch open/close tails, carrier hiss, occasional dropout at long distance, background battle bleed when the speaker is in combat. Priority + ducking so important callouts are never cut. Write the full NEW line list needed (all variants, ~400 lines incl. numbers/directions) to Design/Audio/telsiz_replikleri_v2.csv (id,text,stress,category,voiceHint).'],
  ['A4-turkce-ses-uretimi', 'Better Turkish voice generation on this Mac (no paid API, no user accounts). Try in order, inside the scratchpad/a venv, never system-wide: (a) Piper TTS (pip install piper-tts) with Turkish voices tr_TR-dfki-medium / tr_TR-fahrettin-medium / tr_TR-fettah-medium downloaded from the official rhasspy/piper-voices Hugging Face repo — CHECK and record each voice model license; (b) if Piper fails, macOS voices (say -v "?" | grep tr) incl. enhanced/premium Yelda. Generate ALL lines in Design/Audio/telsiz_replikleri.csv plus any rows already present in Design/Audio/telsiz_replikleri_v2.csv (another agent is writing it; if not there yet, generate the A3 core barks list yourself: Şarjör!, El bombası!, Yaralandım!, Düşman düştü!, Bana ört!, İlerliyorum!, Sis atıyorum!, Emredersiniz komutanım, saat 1..12 yönü, 50/100/200/300/400 metre) with 3+ distinct voices and 3 stress variants (sakin: normal rate; çatışma: faster, louder; panik: fastest, higher pitch, shorter pauses — via length_scale/noise params or sox/afconvert post), normalize to -16 LUFS approx (use ffmpeg loudnorm if available, else peak-normalize), 22.05 kHz mono WAV into Assets/_Project/Resources/Audio/Voice/v2/<voice>/<stress>/<id>.wav and a voice_manifest_v2.json. Keep the old Voice/ files untouched. Report total size. Write Docs/SES_TTS_NOTU.md update with licenses and the recommendation that final release uses real Turkish voice actors (write a recording script Docs/SESLENDIRME_SENARYOSU.md: roles, tone, mic/distance notes, line list reference).'],
  ['A5-ortam-hdr-miks', 'Infrastructure/Audio/Mix/* + Infrastructure/Audio/Ambience/*: HDR audio mixing (Frostbite-style: a running loudness window — when very loud events happen (explosions, own MG fire), quiet sounds (footsteps far, ambience) are pushed below the window instead of clipping; pure HdrAudioMath + tests); runtime mix snapshots without an AudioMixer asset dependency (or with an optional mixer if found in Resources): kulak çınlaması/tinnitus after close explosion (ring tone + muffled world 3–6 s), underwater, indoor, ADS focus (slight ambience duck), death/downed muffle; ambience beds per map biome + time of day + weather: mountain wind gusts, pine forest birds (day), insects/owls/dogs (night), village life (rooster, dogs, call-to-prayer-free generic distant village), rain on surfaces/roof when indoors, distant battle (other teams fighting far away: occasional distant gunfire and explosions heard over the valley, scheduled from real match events if available via EventBus, else synthetic). All procedural fallbacks via ProceduralAudioSynth API (read it), clips from Resources/Audio/Ambience/<biome>/ if present.'],
]
phase('G5 Ses')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G5 Ses', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
