export const meta = {
  name: 'harekat-codfeel-g17',
  description: 'HAREKÂT G17 CoD hissi: ADS girişi (aç/kapa + basılı), nişangâh hizalama/kalite, FP animasyon v2, FP namlu efektleri, isabet hissi, düşman ayırt edilebilirliği, GC temizliği (7 Sonnet ajanı)',
  phases: [{ title: 'G17', detail: '7 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g17_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 URP C# at ${ROOT}, Turkish UI. Owner target: modern CoD-MW gunfeel — snappy, readable, satisfying. ~20 parallel agents; disjoint scopes; stay in YOUR files; cross-file → "ENTEGRASYON: <file>: <call>" in concerns. Other waves own: World/LocationBuilder, MapLayout*, TerrainGenerator/Erosion, RockScatter, TerrainPainter, WorldWater/WaterSurface/Ice, WeaponModelFactory, SoldierModel attach, PingWorldView, UiKit, MainMenuController. Grep APIs first.
Do NOT launch Unity. Verify: ${V(id)} (0 errors in your files; others' in-flight errors not yours). Pure logic + EditMode tests. No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. One dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük".`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['A1-ads-giris', 'SCOPE: Presentation/Player/PlayerWeaponHandler.cs (aim input path), Core GameSettings + Application SettingsService (ADS fields), Presentation/UI/SettingsPanel.cs (rows only). OWNER BUG: "sağ tık yapınca nişan almıyor, basılı tutmam gerekiyor" — the toggle-ADS option either defaults off, is broken, or right-click press is missed. Fix: (1) grep the existing aç/kapa ADS accessibility setting; make TOGGLE mode work flawlessly (press toggles in/out, cancel on sprint/reload option) and HOLD mode stay default-correct; expose setting "Nişan: Bas-Tut / Aç-Kapa" clearly in AYARLAR→Oyun; (2) input edge robustness: use WasPressedThisFrame for toggle (not IsPressed), never eat the frame; (3) ADS timings snappy per weapon (AdsTime from catalog) with SmoothDamp, no first-frame hitch; (4) auto-lower cancel: firing from hip right after ADS exit must not be blocked. Tests for the toggle state machine.'],
  ['A2-nisangah', 'SCOPE: new Infrastructure/Weapons/SightAlignment.cs + SightVisuals.cs, Presentation/UI/CrosshairView.cs. OWNER: "nişangâhlar çok küt" (clunky). Fix: (1) ADS alignment: compute the eye-to-sight transform so rear aperture + front post (or red-dot) land EXACTLY on screen center during ADS (pure math API: SightAlignment.EyeOffset(weaponId, sightType) from the model sockets — grep Sight socket); expose for WeaponViewModel (ENTEGRASYON one call line); (2) red dot: crisp 2-3 px HDR dot with soft glow, parallax-stabilized; iron sights: thin dark post, not fat blocks — adjust sight mesh params in SightVisuals (new; reads WeaponBlueprints sight builders via public API or ENTEGRASYON); (3) hip crosshair: modern 4-line dynamic spread (expands with movement/fire via existing spread data), center dot optional, thin 2 px lines with 1 px shadow, hidden in ADS; kill X slight scale-pop 80 ms.'],
  ['A3-fp-anim-v2', 'SCOPE: Infrastructure/Weapons/WeaponViewModel.cs (motion only), Application/Services/ViewmodelDynamics.cs. CoD-modern FP motion: stance-specific bob curves (walk subtle figure-8, sprint strong canted pose with gun across chest, crouch tight, prone minimal), ADS breath sway (slow 0.3 Hz, tighter with hold-breath API if present), jump: gun lifts, land: dip with recovery overshoot, turn: weapon lags 2-4° with spring return, strafe: roll 1-2°, slide: gun to hip canted. All framerate-independent via ViewmodelDynamics springs; respect Suppression.SwayMultiplier; call SightAlignment API if present for ADS anchor (reflection-safe). Tests for curve bounds.'],
  ['A4-fp-vfx', 'SCOPE: Infrastructure/Vfx/** (muzzle/shell/heat files; not FootprintTrail). First-person-visible gunfire polish: muzzle flash shorter (1-2 frame) and shaped per device (flash hider star, suppressor puff), subtle screen-space light spill on walls, heat shimmer quad over barrel after sustained fire, shell ejection arc visible in FP with brass glint, lingering muzzle smoke wisp after burst (2 s), tracer start offset so it does not spawn inside camera. Budget-pooled; tier limits.'],
  ['A5-isabet-his', 'SCOPE: Presentation/UI/HitFeedbackDirector.cs + new Presentation/UI/DamageNumbersView.cs, Infrastructure/Audio hit-sound selection (small: GameAudio public hook or new Audio/HitTones.cs). CoD hit feel: hitmarker sound pitch rises with damage, distinct armor "clink" vs flesh "thock", kill confirm sound + killfeed flash; optional floating damage numbers (default OFF, setting "Hasar sayıları" — ENTEGRASYON SettingsPanel row via A1 if file contention, else PlayerPrefs), stacking numbers combine, headshot gold; assist toast. Pure rules + tests.'],
  ['D1-dusman-ayirt', 'SCOPE: Infrastructure/Characters/SoldierLook.cs (+ its texture helpers). Readability: enemies must read instantly at 50-300 m — enemy team: slightly darker uniform tint + red armband/helmet band; friendly: existing. Boost silhouette contrast vs terrain (rim-light friendly values are rendering-side; here adjust albedo separation), remove any same-palette confusion between teams. Keep camo system working; colorblind-safe (band shape differs too: enemy diagonal stripe).'],
  ['D4-gc-temizlik', 'SCOPE: hot-path alloc fixes ONLY in: Infrastructure/Combat/BallisticsSystem.cs, Infrastructure/AI/BotPerception.cs, Infrastructure/Audio/GameAudio.cs (alloc hotspots), Presentation/UI/HudController.cs string churn. Find per-frame allocations (new arrays/lists/strings/closures/LINQ in Update/Tick paths — grep foreach over dictionaries, string.Format in per-frame): replace with cached buffers, StringBuilder, for-loops; no behavior change. Report before/after alloc sites count. Tests must stay green.'],
]
phase('G17')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G17', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
