export const meta = {
  name: 'harekat-content-7',
  description: 'HAREKÂT dalga 7 içerik: yeni Türk silahları, Cobra aracı, gece görüş, konvoy ve rehine modları, test kapsamı (6 Sonnet ajanı)',
  phases: [{ title: 'Dalga 7', detail: '6 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${ROOT}/Tools/UnityVerify/out_${n} --player --tests`
const RULES = `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6 C# at ${ROOT}. Editor can't run here; verify with ${V('<name>')} — keep 0 errors, all tests passing (502).
Read ${ROOT}/ARCHITECTURE.md sections you need. TOKEN-EFFICIENT: open only needed files (grep). Prefer NEW files in your scope; small null-safe edits elsewhere.
No deletes/.meta/file-changing git. UnityEngine.Application inside Project.* namespaces. Turkish UI. Procedural content. Add EditMode tests for pure logic
(tests that need Infrastructure/Presentation must be wrapped in #if UNITY_EDITOR). Cursor is concurrently fixing real-Unity errors anywhere; 7 other Claude agents run in parallel —
stay strictly in your scope.  Append a dated line to ${ROOT}/Docs/DURUM.md "Günlük" when done.`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const F = [
  ['silahlar2', `New Turkish weapons (keep existing ids stable, append): Sarsılmaz SAR 223 (5.56 AR), MKE MPT-76 kısa namlu "MPT-76K" (7.62 carbine), Canik METE SFT (9mm pistol), Sarsılmaz SAR 762 MT? (use "SAR 762 MT" 7.62 DMR), MKE MG3 "MG3" (7.62 belt MG, very high RPM), Akdaş "AK-12 pompalı"? NO — use fictional-safe "Escort Magnum" 12ga semi-auto. Add WeaponIds + WeaponCatalog entries (balanced vs existing), ItemCatalog weapon items, LootSpawnService tier tables, procedural models in Infrastructure/Weapons/WeaponModelFactory (+ new mesh builder file), sounds via existing class mapping, Design/Wiki unaffected. Tests for catalog consistency.`],
  ['cobra', `Second drivable vehicle "Otokar Cobra" (4x4 light armored vehicle, faster, less armor, 6 seats, roof 12.7 mm-style MG): new files in Infrastructure/Vehicles (CobraModelBuilder + config) reusing DrivableVehicle with a VehicleConfig abstraction (refactor minimally: extract tunables into a VehicleConfig ScriptableObject-free class; Kirpi behaviour unchanged). Spawn some Cobras at village/outpost vehicle spawns (LocationBuilder vehicle spawns already exist — choose type by location). Seat/turret/crew boarding reuse.`],
  ['gece-gorus', `Night vision goggles (Gece Görüş Gözlüğü): equipment item (ItemCatalog, loot Military tier, part of Leader/Radioman loadout on Gece time of day), toggle key N? (N is tutorial skip only in training) — use binding "NightVision" default Key.L if L free else Key.O (check ControlScheme reserved list), green post effect (Infrastructure/Rendering new NightVision*.cs: color filter, noise, vignette, exposure boost, flashlight bloom), battery 120 s recharge, works with Atmosphere night preset; bots get worse perception at night unless equipped. Scope new files + small hooks (InputBindings, PlayerController toggle, BotPerception range multiplier).`],
  ['konvoy', `New mode "Konvoy Koruma" (escort): 2 teams of 10 on KuzgunVadisi; attackers ambush along the main road; defenders escort 3 procedural supply trucks (reuse Kirpi visual scaled or a simple truck builder) that drive a road path waypoint route; trucks have HP; defenders win if ≥1 truck reaches the end, attackers win if all destroyed or defenders eliminated; respawn waves 25 s. New Presentation/Bootstrap/ConvoyBootstrap.cs + Application ConvoyRules (pure, tests) + menu entry via MainMenuController.ExtraButtons registration (do not edit MainMenuController).`],
  ['rehine', `New mode "Rehine Kurtarma" (hostage rescue): attackers (player team) must reach a building in Kuzgun Köyü / Yıkık Köy, find 2 hostages (unarmed NPCs using SoldierModel civilian look), escort them (follow when F pressed) to an extraction LZ where a T-70 lands; defenders (AI team of 10) guard; time limit 8 min; no respawn; hostage death = fail. New Presentation/Bootstrap/HostageBootstrap.cs + Infrastructure/AI/HostageNpc.cs (new file, simple follow NavMesh) + Application HostageRules (pure, tests) + menu entry via ExtraButtons.`],
  ['testler', `Raise EditMode test coverage of Application + Core (pure C# only, no Unity): MatchService edge cases (simultaneous deaths, downed wipes), ZoneService over many seeds, InventoryService capacity/attachments, ItemUseService/BoostService, CombatService friendly-fire & armor wear, ChainOfCommandService transfers, ArtilleryService scheduling, AchievementService metrics, LocalizationTable, ControlScheme conflicts. Add only tests (and fix real bugs found in Application/Core with minimal edits). Target +80 tests, all passing in the shim (NUnit subset: Assert.AreEqual/IsTrue/IsFalse/IsNull/IsNotNull/Greater/Less/Throws/Contains — no Assert.That).`],
]
phase('Dalga 7')
const out = await parallel(F.map(([k, task]) => () => agent(`${RULES}\nTASK ${k}: ${task}`, { label: k, phase: 'Dalga 7', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
