export const meta = {
  name: 'harekat-dev-g13',
  description: 'HAREKÂT G13: viewmodel animasyon tamamlama, izler+gece, harita UI, yükleme ekranı, envanter UI, dinamik hava, poligon, araç hissi, silah-başına gerçek ses, netcode, PlayMode testleri, kamuflaj içerik (12 Sonnet ajanı)',
  phases: [{ title: 'G13 Geliştirme', detail: '12 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g13_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 URP C# at ${ROOT}, UGUI + LegacyRuntime font, Turkish UI. You are one of 12 parallel agents; a separate wave (G12) owns Infrastructure/AI/**, Combat/BallisticsSystem.cs, Infrastructure/Player/**, Presentation/Player/PlayerController.cs, Presentation/UI/Hud*/Compass*/Killfeed*/HitMarker*/DamageIndicator*/AmmoCounter*, Spectator*/Death*/Downed*/Revive*, MainMenu*/Loadout*, Characters/SoldierModel*; others own Editor/ThirdParty/** and World/BuildingGenerator*. STAY strictly in your task's scope; for calls into others' files write "ENTEGRASYON: <file>: <call>" in concerns instead of editing.
Read existing code first (grep) and IMPROVE it — no rebuilds, no throwaway work. Deliver working code only.
Do NOT launch Unity. Verify with ${V(id)}: 0 errors in your files, all tests passing (baseline 1348+). EditMode tests for pure logic (NUnit shim subset; Infrastructure-dependent tests in #if UNITY_EDITOR). No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. Append one dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük".`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['W1-viewmodel-anim', 'SCOPE: Infrastructure/Weapons/WeaponViewModel*.cs + Application/Services/ViewmodelPoseTimeline.cs. Finish the keyed-timeline animations: MG belt reload (top cover open, belt lay, close) and shotgun shell-by-shell (with interrupt on fire) on the timeline; weapon inspect (BindAction.Inspect, key K) with 2-phase turn/tilt look; equip/holster draw curves; use the NewMagInHand track so a second magazine appears in the left hand while the old one drops; sprint tactical pose transition. Keep all existing public signatures and procedural fallbacks.'],
  ['W2-izler-gece', 'SCOPE: Infrastructure/Vfx/** only. Visible bullet tracers (thin stretched emissive quad following the real ballistic path, every 3rd round + all MG rounds, brighter at night), muzzle light (brief point light flicker synced to shots, cheap pooling, tier-limited), enhanced night combat visuals (tracer glow via bloom-friendly HDR color, explosion light flash), smoke volume light scattering fake (brighten smoke near flashes). Expose GameVfx.Tracer(origin, dir, speed, caliber) and list ENTEGRASYON line for BallisticsSystem (owned by G12 Q1).'],
  ['W3-harita-ui', 'SCOPE: Presentation/UI/Map*.cs, Minimap*.cs (not Hud*). AAA map experience: full-screen map with terrain-colored render (reuse existing minimap texture pipeline), grid + coordinates (karelaj, e.g. 18S VK 123 456 style simplified), zoom/pan with mouse, squad member icons with rank + view cones, ping placement (left click) + danger ping, zone current/next circles with timer, vehicle icons, distance measure tool (right-drag), killed-teammate markers. Minimap: north-up/rotating toggle, zone edge indicator arrow, nicer frame.'],
  ['W4-yukleme-ekrani', 'SCOPE: new Presentation/UI/LoadingScreen*.cs + Presentation/Bootstrap loading flow hook points (one-line calls only, guarded). Loading screen between menu and match: map name + Turkish tactical tips rotation (write 40 tips: weapon handling, armor, zone, squad comms), stylized map silhouette drawn procedurally (reuse map layout data), progress bar driven by real load phases (scene load, world gen, bot spawn — find the phases in MatchBootstrap, expose LoadingScreen.Report(phase, 0..1) and list ENTEGRASYON lines if the bootstrap files are owned by others... MatchBootstrap is NOT owned by G12: you may add the minimal Report calls yourself, null-safe), insertion briefing text (map + mode + tim count).'],
  ['W5-envanter-ui', 'SCOPE: Presentation/UI/Inventory*.cs. Modernize the Tab inventory: grid slots with item icons (procedural icon drawing per ItemCategory + weapon silhouettes already exist — grep icon code), drag-drop equip/drop, armor/helmet durability bars, weapon card with attachment slots visual, ammo-by-caliber summary row, ground loot list sorted by distance with rarity colors, quick actions (use/drop/split), controller/keyboard navigation, rarity color coding consistent with loot beams. Keep InventoryService API unchanged.'],
  ['W6-dinamik-hava', 'SCOPE: new Infrastructure/Rendering/WeatherSystem*.cs + Core pure WeatherTimeline (tests). In-match dynamic weather: seeded timeline per match (e.g. Açık → bulutlanma → yağmur → açılma), smooth transitions over 60-120 s driving Atmosphere.ApplyEnvironment weather params gradually (grep its API; call it, do not edit it), distant rain curtain visual before rain arrives, lightning: flash (directional light pulse + sky brighten) then thunder via GameAudio with distance delay (ENTEGRASYON line if Audio call unclear), wind strength follows weather (WindSystem.SetWeather). Server-authoritative: timeline from match seed; MatchConfig flag to disable. One-line hook into MatchBootstrap allowed (null-safe).'],
  ['W7-poligon', 'SCOPE: Presentation/Bootstrap/TrainingBootstrap.cs + Presentation/Training/** (new) + existing training challenge code (grep Training). Make the Poligon a real training mode: numbered lanes with distance markers (100-600 m), pop-up targets with hit zones + reaction time scoring, moving targets on rails, a timed shoot-house course (procedural rooms, hostage no-shoot targets, par time, star rating), grenade pit, vehicle test pad with Kirpi + T-70, scoreboard UI with best times (ISettingsStore persistence), Turkish range officer barks via existing dialogue API.'],
  ['W8-arac-hissi', 'SCOPE: Infrastructure/Vehicles/** + Infrastructure/Transport/KirpiTurret*.cs (grep). Vehicle feel: Kirpi suspension visual (body roll/pitch from acceleration, wheel bounce), engine audio pitch by RPM + gear steps (hook GameAudio or own AudioSource pool — Audio/** files owned by W9: use public APIs only, else ENTEGRASYON), tire dust/mud kickup via GameVfx, dashboard HUD when driving (speed, heading, damage diagram), turret feel: traverse speed limits + motor whine hook, gunner camera with stabilization toggle, horn (H), headlights (L conflict? grep InputBindings — pick free key) lighting actual spotlights at night, damage states smoke/fire from engine at low HP.'],
  ['W9-silah-ses-v2', 'SCOPE: Infrastructure/Audio/** only. Real-clip polish: per-weapon folders from _class sets where distinct (copy/choose best clips into Resources/Audio/Weapons/<weaponId>/ via an EDITOR utility script under Editor/Audio/ — new file allowed there), improve procedural bullet crack/whiz (layered noise burst + doppler-ish pitch), add MG3 belt rattle layer synth, suppressed shot variants (filtered bang + mech emphasis), interior gunshot variant auto-selection check, loudness pass: verify all fire layers within -1 dBFS peak and consistent LUFS per class (write a pure LoudnessMath + tests), bullet impact sounds per SurfaceKind from real clips if present. Do not break WeaponFoley API.'],
  ['W10-netcode', 'SCOPE: Assets/_Project/Scripts/Online/** only. Harden for real multiplayer: client-side prediction + reconciliation scaffolding for PlayerCommand (sequence numbers, server ack, replay buffer — pure logic + tests), snapshot interpolation with adaptive buffer (jitter-based), lag compensation rewind data structure for hitscan (ring buffer of combatant positions, 1 s at 30 Hz, pure + tests), interest management (only replicate entities within 500 m or same tim), bandwidth budget accounting per client, and HAREKAT_NETCODE-gated NetworkPlayer improvements matching these. Keep OfflineNetworkSession behavior identical.'],
  ['W11-playmode-test', 'SCOPE: Assets/_Project/Tests/PlayMode/** only. New smoke tests (follow existing PlayMode test patterns/helpers): AAA_Benchmark scene loads + Vitrin completes 1 shot + screenshot saved; ragdoll spawns on bot death (kill a bot, assert rigidbodies active then settle); grass system installs on terrain without exceptions; water + sky objects exist in KuzgunVadisi; quality tier switch 0→3→0 at runtime without exceptions; replay recorder writes a file after a short match; suppression driver reacts to a near explosion. Each test bounded < 60 s, robust to missing systems (skip with message rather than fail when a scene lacks a feature).'],
  ['W12-kamuflaj', 'SCOPE: Application/Services/CosmeticsService.cs + CosmeticCatalog data (grep cosmetics.json/catalog), Infrastructure/Characters/SoldierLook.cs ONLY (not SoldierModel*.cs). Content: 8 new procedural camo patterns (çöl, kar, orman dijital, multicam-benzeri, gece, taş, bozkır, şehir) generated in ProceduralTextures-style code within SoldierLook/its texture helper, 6 face paint styles, 4 helmet cover variants, ghillie bits for sniper role; weapon camo wraps using same palettes (hook via existing WeaponStyle camo field if present — grep; else ENTEGRASYON note); register all in CosmeticCatalog with rarity + season pass references (append-only, keep ids stable), unlock rules; update Design copy of catalog json identically.'],
]
phase('G13 Geliştirme')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G13 Geliştirme', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
