export const meta = {
  name: 'harekat-features-4',
  description: 'HAREKÂT dalga 4: 8 Sonnet ajanı (düzeltme paketi, online kimlik, yaralı düşme+sıhhiye, İHA keşfi, skor tablosu, gelişmiş ayarlar, Mavi Liman haritası, kozmetikler)',
  phases: [{ title: 'Dalga 4', detail: '8 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${ROOT}/Tools/UnityVerify/out_${n} --player --tests`
const RULES = `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6 C# at ${ROOT}. Editor can't run here; verify with ${V('<name>')} — keep 0 errors, all tests passing (451).
Read ${ROOT}/ARCHITECTURE.md sections you need. TOKEN-EFFICIENT: open only needed files (grep). Prefer NEW files in your scope; small null-safe edits elsewhere.
No deletes/.meta/file-changing git. UnityEngine.Application inside Project.* namespaces. Turkish UI. Procedural content. Add EditMode tests for pure logic
(tests that need Infrastructure/Presentation must be wrapped in #if UNITY_EDITOR). Cursor is concurrently fixing real-Unity errors anywhere; 7 other Claude agents run in parallel —
stay strictly in your scope.  Append a dated line to ${ROOT}/Docs/DURUM.md "Günlük" when done.`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const F = [
  ['duzeltme', `Fix pack (small edits): (1) ServerBootstrap -map must actually load the chosen scene (Scripts/Online/Netcode/ServerBootstrap.cs + GameSession scene load path: use SceneNames.OperationSceneFor(GameSession.SelectedMap) wherever the operation scene is loaded, incl. Presentation/DevTools/DevConsoleCommands.cs line ~702); (2) dev console "ai" command prints BotLod.StatsLine; (3) TrainingRangeBuilder adds 1 vehicle spawn and TrainingBootstrap spawns a DrivableVehicle there so the tutorial vehicle step works; (4) read the last ~15 lines of Docs/DURUM.md "Günlük" and fix any remaining small concerns that are clearly bugs and fit in a few lines. Scope: those files only.`],
  ['online-kimlik', `Scope Scripts/Online/** only. Map connections to backend identities: client sends its JWT/join ticket in Netcode ConnectionApproval payload; ServerBootstrap validates it with the backend (/matchmaking ticket check endpoint as documented in Backend/README.md or Backend/Harekat.Api — read-only) and calls RegisterPlayerProfile/RegisterTeamSquad so results carry real Guids; filter bots out of the submitted results (or mark IsBot). Run verify_online.sh.`],
  ['yarali', `Downed/revive (DBNO) for squads: when HP reaches 0 and an ally is alive within the team, the combatant is "Yaralı" (crawls, cannot shoot, bleeds out over 45 s, finishable by enemies); allies revive with F hold 6 s (Sıhhiyeci 3 s); bots: medic/nearest ally revives when safe. Implement pure state in Application (new ReviveService + tests, events DownedEvent/RevivedEvent in Core), integrate in Infrastructure/Combat/Combatant.cs (minimal), Infrastructure/AI (new file BotReviveBehaviour.cs + small hook in BotController.Brain), Presentation/Player (revive interaction + downed camera/crawl), HUD prompt. MatchService must count downed-team-wipe as elimination. Keep offline solo play sane (if no ally alive → die immediately).`],
  ['iha', `Recon drone (İHA keşfi) for Radioman/Leader: key U (unless bound) launches a small procedural drone that flies to the aim point at 80 m altitude for 12 s and marks enemies within 60 m on minimap/compass/world (red diamonds) for the team; 120 s cooldown per team; sound loop. New files Infrastructure/Drone/*.cs + Presentation/UI/ReconMarkersView.cs, small hook in Presentation/Player/SquadCommandInput.cs and AI commanders may use it. Pure cooldown/marking logic in Application with tests.`],
  ['skor', `Scoreboard: hold CapsLock (UiInputState.HoldScoreboard) or Tab-hold variant → full scoreboard overlay: teams sorted by alive/placement, each member with rank-formatted name, role icon, kills, damage, status (alive/downed/dead), ping placeholder; local team highlighted. New Presentation/UI/ScoreboardView.cs + one-line creation hook in GameplayUiController. Data from MatchService/MatchStatsService/CombatantRegistry. No per-frame allocations (refresh 4 Hz).`],
  ['ayarlar', `Advanced settings in Presentation/UI/SettingsPanel.cs + Core GameSettings + SettingsService: resolution & window mode (Screen.resolutions), VSync, frame-rate cap (30/60/120/144/unlimited), render scale, separate volume sliders (Efekt, Müzik/Ortam, Telsiz/Ses), crosshair color/size, HUD scale, motion blur off/on placeholder, colorblind mode (deuteranopia palette for ally/enemy colors via UiTheme). Apply immediately, persist, add Loc keys with Turkish fallback.`],
  ['harita3', `Third map "Mavi Liman" (coastal town). Input Design/Maps/v2/MaviLiman/layout.json + README. Mirror what was done for Ayaz Geçidi (read Infrastructure/World/MapLayoutAyazGecidi.cs, MapCatalog, SceneNames, Editor/SceneBuilder EnsureAyazGecidi): new MapLayoutMaviLiman.cs, sea water plane at edge, beach sand painting, harbor/lighthouse/olive grove props via existing PropFactory/BuildingGenerator calls, map entry in MapCatalog + menu selector + SceneBuilder + build settings.`],
  ['kozmetik', `Cosmetics from Design/Progression/cosmetics.json (copy to Resources/Progression/cosmetics.json): pure CosmeticsService (owned/equipped, unlock by rank/achievements, persist via ISettingsStore, tests); apply equipped camo variant/beret color/armband pattern to the player SoldierModel (via SoldierLook) and weapon skin tint via WeaponModelFactory material override (small hook); new Presentation/UI/CosmeticsPanel.cs ("KOZMETİK" button registered through MainMenuController.ExtraButtons at BeforeSceneLoad — do NOT edit MainMenuController). Cosmetic only, no stats.`],
]
phase('Dalga 4')
const out = await parallel(F.map(([k, task]) => () => agent(`${RULES}\nTASK ${k}: ${task}`, { label: k, phase: 'Dalga 4', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
