export const meta = {
  name: 'harekat-features-3',
  description: 'HAREKÂT dalga 3: 8 Sonnet özellik ajanı (AI LOD, online eksikleri, Kirpi tim taşıma+taret, atmosfer/gece, komut çarkı+ping, telsiz replikleri, çatışma modu, silah eklentileri)',
  phases: [{ title: 'Dalga 3', detail: '8 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${ROOT}/Tools/UnityVerify/out_${n} --player --tests`
const RULES = `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6 C# at ${ROOT}. Editor can't run here; verify with ${V('<name>')} — keep 0 errors, all tests passing (429).
Read ${ROOT}/ARCHITECTURE.md sections you need. TOKEN-EFFICIENT: open only needed files (grep). Prefer NEW files in your scope; small null-safe edits elsewhere.
No deletes/.meta/file-changing git. UnityEngine.Application inside Project.* namespaces. Turkish UI. Procedural content. Add EditMode tests for pure logic
(tests that need Infrastructure/Presentation must be wrapped in #if UNITY_EDITOR). Cursor is concurrently fixing real-Unity errors anywhere; 7 other Claude agents run in parallel —
stay strictly in your scope. Never edit Presentation/Tutorial/*, TrainingBootstrap.cs, TrainingRangeBuilder.cs (another agent). Append a dated line to ${ROOT}/Docs/DURUM.md "Günlük" when done.`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const F = [
  ['ai-lod', `Scope Infrastructure/AI/*. Bot update LOD for 60 bots: full rate near the local player / in combat; reduced perception/decision/animation rates beyond 120 m and 250 m; skip SoldierModel animation updates when off-screen (renderer isVisible) or very far; cap simultaneous path requests; keep combat fairness (a far bot that is being shot or shooting goes to full rate). Add an AI stats line for the dev console if simple.`],
  ['online-eksik', `Scope Scripts/Online/** plus minimal edits in Presentation/Player/PlayerWeaponHandler.cs and Infrastructure/Combat/ArtilleryExecutor.cs. (1) Non-authority clients: grenade throw and melee send requests to the server (new request structs in Core/Domain if needed, routed via INetworkSession/IPlayerCommandSink) instead of early-returning; (2) artillery/explosion VFX+audio for clients via ExplosionEvent relay (damage only on authority); (3) richer per-player match results: GameSession.MatchFinished payload extension or new event with all combatants' stats so ServerBootstrap submits real team/player results; (4) backend matchId plumbing into ServerBootstrap from allocation args (-matchId). Keep offline unchanged. Run Tools/UnityVerify/verify_online.sh too.`],
  ['kirpi-tim', `Scope Infrastructure/Vehicles/*, plus small hooks in Infrastructure/AI (only a public method to board/unboard if needed — coordinate by adding NEW file Infrastructure/AI/BotVehicleBoarding.cs rather than editing BotController) and Presentation/Player/PlayerController.cs (vehicle enter only). Drivable Kirpi: squad teammates board as passengers when the player (commander) drives and issues F1 Follow (seat assignment, hidden/seated model, disembark on stop + F4 Regroup); a usable roof-mounted 7.62 MG turret for a passenger seat (player can switch seats with 1-2 keys while in vehicle) firing through BallisticsSystem; vehicle HUD info (speed, health) via existing notification/HUD hooks.`],
  ['atmosfer', `Scope NEW files Infrastructure/Rendering/Atmosphere*.cs (+ small hook calls in PostProcessing/RenderSettingsUtil and in MatchBootstrap Start: one line). Time of day presets (Şafak, Gündüz, Akşam, Gece) with sun angle/color, ambient, fog, skybox tint, post-process exposure; night mode with limited visibility + muzzle flashes stronger + optional flashlight on weapon (F key held? use L key) for player; light rain/snow particle option (snow default on Ayaz Geçidi). MatchConfig gets TimeOfDay + Weather fields (Core model) and main menu setup panel selectors (small edit in MainMenuController setup section).`],
  ['komut-carki', `Scope NEW Presentation/UI/CommandWheel*.cs, Ping*.cs and small edits in Presentation/Player/SquadCommandInput.cs. (1) Hold Caps/Mouse4? use key "Q"? NO — use Middle mouse hold or "Y" hold to open a radial command wheel: Takip, Mevzi al, Taarruz (aim point), Toplan, Topçu iste, Sis at; release to choose; time slows only offline. (2) Ping: Middle-click quick = place a world ping (enemy if aiming at an enemy combatant → red "Düşman!" marker for team for 8 s, else location marker) shown in world-space HUD + minimap (use existing MapMarkers / AllyMarkersView APIs read-only, add new view if needed); bots react to enemy pings by investigating.`],
  ['telsiz', `Scope NEW Infrastructure/Audio/Radio*.cs + Presentation/UI/RadioSubtitleView.cs. Input: Design/Audio/telsiz_replikleri.csv (copy needed columns to Resources/Audio/radio_lines.json). Radio chatter system: on events (contact spotted by AI teammates, reload, ally down, order acknowledgements F1–F4, command transfer, artillery requested/inbound, zone shrinking, team eliminated, victory) pick a line by key/role, play a radio squelch+beep (GameAudio RadioBeep/RadioChatter) and show subtitle "[Rütbe Ad]: metin" bottom-left for 3 s, with cooldowns and priority so it never spams. Hook by subscribing to IEventBus via GameContext (no edits to other systems unless a needed event is missing — then add it minimally).`],
  ['catisma-modu', `Scope NEW Presentation/Bootstrap/SkirmishBootstrap.cs (+ small edits: SceneNames/GameSession/MainMenuController to add "ÇATIŞMA (Hızlı Maç)"). Quick mode reusing the KuzgunVadisi scene: 2 teams × 10 in one location region (pick a random LocationSpec, e.g. Kuzgun Köyü vs Sınır Karakolu sectors), ground spawn (no insertion), respawn waves every 20 s at team base, first team to 50 kills or most kills after 10 min wins; zone disabled; HUD score bar. Reuse MatchBootstrap pieces through composition (do not rewrite MatchBootstrap; if a helper must be extracted, keep MatchBootstrap behaviour identical).`],
  ['eklentiler', `Weapon attachments. Scope: NEW Application/Catalogs/AttachmentCatalog.cs + Application/Services/AttachmentStats.cs (pure, with tests), item entries in ItemCatalog (red dot "Kırmızı Nokta", 2x/4x dürbün, susturucu, uzatılmış şarjör, dikey tutamak, nişancı dipçiği), InventoryService support for attaching to the active weapon (auto-attach on pickup if compatible slot empty), WeaponRuntimeService reads modifiers (mag size, recoil, spread, ADS zoom, suppressed flag), WeaponModelFactory adds simple visual parts on the weapon model, suppressed shots quieter/no tracer in GameAudio.PlayGunshot/BallisticsSystem (tiny edits). LootSpawnService tables include attachments. Do not edit PlayerWeaponHandler (another agent).`],
]
phase('Dalga 3')
const out = await parallel(F.map(([k, task]) => () => agent(`${RULES}\nTASK ${k}: ${task}`, { label: k, phase: 'Dalga 3', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
