export const meta = {
  name: 'harekat-g14c',
  description: 'HAREKÂT G14c: eğitim/öğretici, kariyer derinliği, ragdoll ayarı, yeni el bombaları, su/ıslak cila, erişilebilirlik+kontrast taraması (6 Sonnet ajanı)',
  phases: [{ title: 'G14c', detail: '6 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g14_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 URP C# at ${ROOT}, Turkish UI. ~20 parallel agents, disjoint scopes — stay in YOUR files; cross-file needs → "ENTEGRASYON: <file>: <call>" in concerns. Grep first, improve existing code; working code only.
Do NOT launch Unity. Verify with ${V(id)}: 0 errors in your files (others' in-flight errors are not yours). EditMode tests for pure logic. No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. One dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük".`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['F15-ogretici', 'SCOPE: Presentation/Tutorial/** only. First-time player onboarding: contextual tip popups on first occurrences (first loot, first ADS, first zone warning, first downed teammate, first vehicle) with "bir daha gösterme" persistence; interactive basic-training flow in the Poligon scene (move→shoot→reload→grenade→heal checklist with checkmarks and Turkish VO hooks via dialogue API ENTEGRASYON); input hints adapt to gamepad; tutorial completion grants a cosmetic (CosmeticsService API read-only, ENTEGRASYON if grant call needs their file).'],
  ['F16-kariyer', 'SCOPE: Application/Services/MatchStatsService.cs, ProgressionService (grep), new Application/Services/CareerService.cs + Presentation career UI files ONLY if named Career* (grep; MainMenu owned elsewhere → ENTEGRASYON for the button). Career depth: per-weapon stats (kills, headshots, accuracy, longest kill), per-map stats, rank progression already exists (read), medals/ribbons (30 adet: Keskin Nişancı, Hayalet, Sıhhiyeci...) with tiered thresholds, match history last 20 with placement graph, career level separate from season pass. ISettingsStore persistence, pure rules + tests.'],
  ['F17-ragdoll-ayar', 'SCOPE: Infrastructure/Characters/RagdollRig.cs, RagdollMath.cs, SoldierModel.Ragdoll.cs. Tune death physics to look right (owner watches deaths a lot): realistic mass distribution (total 80 kg spread), joint limits preventing backward-knee/owl-head poses, impulse scaling so rifle hits crumple rather than launch (cap net impulse ~250 N·s, headshot slight snap), explosion lofting capped (no 20 m flights), friction so bodies do not slide on slopes, settle-freeze unchanged. Drop the weapon with inherited velocity + small spin, helmet knock-off on headshot (if helmet object exists on model — grep). Deterministic-friendly: all tunables in RagdollMath constants + tests for impulse caps and limit ranges.'],
  ['F18-el-bombalari', 'SCOPE: Infrastructure/Combat/Throwable*.cs, ExplosionSystem.cs (add-only), Application catalogs APPEND-ONLY at list ends (ItemIds/ItemCatalog — keep network indices stable, add new ids at END; grep the "sona eklendi" pattern used before), LootSpawnService tables (append). New grenades: flashbang (white flash + ring + tinnitus via AudioMix API, effect scales with view angle + distance, bots blinded via BotController public hook ENTEGRASYON), molotov (fire pool area denial, burning damage ticks, fire+smoke VFX via GameVfx, spreads slightly on slopes, extinguished by rain ENTEGRASYON WeatherSystem), decoy grenade (periodic fake gunshots through Acoustics API to confuse bots — bots investigate via existing hearing). Throw arc preview line for all throwables (dotted trajectory while holding G, existing input read-only). Tests for pure timing/damage rules.'],
  ['F19-su-islak-cila', 'SCOPE: Infrastructure/Rendering/WaterSurface*.cs, WorldWater.cs + Shaders/Water/** (new shader allowed, URP 17 syntax, 1.0h-style half literals). Water polish to PUBG coast quality: gentle directional waves (2-3 gerstner-ish vertex waves in shader), shore wetness darkening band on terrain at waterline (via existing wetness/global or a projected quad), foam only where waves meet shore, underwater: blue-green fog + surface seen from below with refraction-ish distortion, splash VFX + ripple rings when players/vehicles/bullets enter water (GameVfx API; bullet hook ENTEGRASYON BallisticsSystem), swim speed unchanged (no gameplay edits). Planar reflection integration kept (read PlanarReflection API).'],
  ['F20-kontrast-tarama', 'SCOPE: Presentation/UI/UiTheme.cs, UiKit* (if present) + a read-only sweep of all Presentation/UI text/icon creation for contrast and overlap fixes applied ONLY in UiTheme/UiKit helpers and the specific faulty lines (small edits allowed across UI files for: text ≥ 4.5:1 contrast via outline/shadow, minimum font sizes at 1080p, overlapping anchors, truncated Turkish strings "..."). Produce Docs/UI_TARAMA.md listing every issue found with file:line and what you fixed vs left (owned by others → ENTEGRASYON). Add a debug overlay (F9) drawing safe-area bounds + HUD element outlines for Cursor-less visual QA screenshots.'],
]
phase('G14c')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G14c', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
