export const meta = {
  name: 'harekat-g14b',
  description: 'HAREKÂT G14b: ufuk/vista, performans otomasyonu, loot görselleri, kapı/iç mekân, oyuncu hasar hissi, tekrar izleyici cilası, destek ateşi görselleri (7 Sonnet ajanı)',
  phases: [{ title: 'G14b', detail: '7 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g14_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 URP C# at ${ROOT}, Turkish UI. Owner demands Steam-PUBG visual quality and zero visible bugs. ~20 parallel agents, disjoint scopes — stay in YOUR files; cross-file needs → "ENTEGRASYON: <file>: <call>" in concerns. Grep first, improve existing code.
Do NOT launch Unity. Verify with ${V(id)}: 0 errors in your files (others' in-flight errors are not yours). EditMode tests for pure logic. No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. One dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük".`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['F8-ufuk-vista', 'SCOPE: Infrastructure/Rendering/SkyEnvironment.cs, SkyMeshes.cs + new Rendering/HorizonVista*.cs. PUBG-style believable horizon: replace the flat silhouette rings with 2-3 layered distant mountain meshes with proper fog-blended gradient (farther = lighter/bluer), parallax between layers as camera moves, haze band at the horizon line, distant forest texture band on nearer vista layer, sun-side atmospheric glow, night: silhouettes darker than sky with stars only above horizon. Guard every generated vertex against NaN (the old ridge produced NaN bounds). Works from any map + menu via existing Atmosphere hook. Keep total vista < 20k tris.'],
  ['F9-performans-oto', 'SCOPE: Infrastructure/Rendering/PerformanceProfile.cs, RenderPipelineInfo.cs + new Rendering/AutoQuality*.cs. Auto quality: on first launch measure 5 s of frame times on the menu (cheap probe) + SystemInfo (GPU name/VRAM/CPU cores) → pick tier 0-3 (write once to settings, user can override); runtime dynamic resolution assist: if avg frame time > 20 ms for 5 s, drop render scale one notch (within tier bounds) and notify once; restore when headroom returns. Also a frame-budget watchdog logging the top offender categories (existing PerfSampler API read-only). Pure decision logic in AutoQualityRules + tests.'],
  ['F10-loot-gorsel', 'SCOPE: Infrastructure/Loot/** (grep LootSpawn/LootPickup visual code; service logic read-only) + new Loot visual files there. PUBG-readable loot: rarity-colored soft light beam column (subtle, 1.2 m, fades past 40 m), ground ring glow per rarity, item mesh gently rotating + bobbing on a cloth/crate base, weapon loot uses the real weapon model (WeaponModelFactory API), stack badge for ammo, pickup feedback (scale pop + sparkle + sound hook ENTEGRASYON if Audio owned), airdrop crate: red smoke + blinking strobe + parachute visual if the airdrop event exposes position (grep AirdropEvent). Tier-limited beam counts; no per-frame allocs.'],
  ['F11-kapi-icmekan', 'SCOPE: Infrastructure/World/WoodenDoor*.cs, BuildingGenerator interior parts ONLY via its public hooks (grep door/window creation; do not restructure the generator), new World/Interior*.cs. Doors: smooth animated open/close with correct pivot, slam on sprint-through, peek-ajar state (hold F), sound hooks (ENTEGRASYON lines), bullet penetration already handled elsewhere — don’t touch. Interiors of enterable houses: simple furniture sets per room type (bed, wardrobe, table+chairs, kitchen shelf, rug, stove with pipe) from PropFactory-style boxes with the new real materials, window light shafts (cheap quad when sun through window), loot spawn anchor points registered so LootSpawnService can use interiors (ENTEGRASYON line if its file is owned). NavMesh-safe (furniture = obstacles).'],
  ['F12-hasar-hissi', 'SCOPE: Infrastructure/Rendering/CombatScreenFx*.cs, Presentation/UI/DamageVignette/HealthView (grep exact names; not Hud/ folder files). Player damage feel like CoD: directional blood splatter overlay quadrant on hit (fades 2 s), intensifying red vignette + desaturation under 35% HP, heartbeat audio hook + pulse sync (ENTEGRASYON if Audio owned), on heal: clean wipe; downed: screen edge darkening + crawl blur; flash white + ring on armor break; subtle camera micro-shake per hit scaled by damage (use existing PlayerCameraFx API read-only). All intensities respect the existing accessibility/shake settings. Pure curves in testable class + tests.'],
  ['F13-tekrar-cila', 'SCOPE: Presentation/Replay/** only. Replay viewer polish: timeline scrubber with kill event markers clickable, playback speed presets UI (0.25/0.5/1/2/4), free camera smoothing + FOV control (scroll), follow-cam shoulder view + first-person toggle per soldier, name tags with health bars over ghosts, kill highlight auto-jump button ("Sonraki ölüm"), damage numbers popping at hit moments from replay data if recorded (grep ReplayData fields; if not recorded, ENTEGRASYON line for recorder), minimap inset showing camera + soldiers, screenshot key F12 in replay too. Keep file format backward compatible.'],
  ['F14-destek-gorsel', 'SCOPE: Infrastructure/Support/** + Application/Services/ArtilleryService visual hooks only (grep; service math read-only). Support fire spectacle: artillery barrage — incoming whistle timed to shell flight, ground impact pre-flash, staggered impact pattern with dirt columns + shockwave rings + lingering smoke + crater decals (GameVfx APIs), danger zone warning smoke marker where it will land; T-129 ATAK pass: rotor sound doppler (ENTEGRASYON if Audio owned), 20 mm impact line walking across ground with dust, rocket trails with smoke, brass rain; killfeed/HUD notifications already exist (read-only). Night: muzzle flashes light the clouds (SmokeGlowPool API if available). Tier-limited particle counts.'],
]
phase('G14b')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G14b', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
