export const meta = {
  name: 'harekat-g14a',
  description: 'HAREKÂT G14a kullanıcı geri bildirimi: lobi sahnesi, menü müziği, nişan hatası, karakter görünümü, hata taraması, saha detayı, bölge duvarı (7 Sonnet ajanı)',
  phases: [{ title: 'G14a', detail: '7 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g14_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 URP C# at ${ROOT}, UGUI + LegacyRuntime font, Turkish UI. Owner played the game and demands: PUBG-on-Steam visual quality, a far more polished lobby with music, better-looking characters, and all visible bugs fixed. You are one of ~20 parallel agents with disjoint scopes — stay strictly in YOUR files; for calls into others' files write "ENTEGRASYON: <file>: <call>" in concerns. Read existing code first (grep) and improve it; deliver working code only, no throwaway work.
Do NOT launch Unity. Verify with ${V(id)}: 0 errors in your files, tests passing (cross-agent in-flight errors in other files are not yours — note and continue). EditMode tests for pure logic. No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. Append one dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük".`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['F1-lobi-sahne', 'SCOPE: Presentation/Menu/** (MenuBackdropBuilder and friends; grep). Owner screenshot: backdrop soldiers FLOAT in mid-air over fog, a campfire burns in empty space, a lone flag floats, a ridge mesh has NaN vertices (Player.log: "HK_MenuRidge" abnormal bounds). Rebuild the lobby backdrop into a grounded, cinematic camp scene: visible ground plane/terrain patch with real ground material, sandbag emplacement, tents + camo net, a parked Kirpi and a T-70 on a helipad behind, soldiers STANDING/SITTING on the ground around the campfire (use SoldierModel poses; feet on ground), flag on a proper flagpole with cloth sway, dusk sun + warm campfire light + smoke, slow 30 s camera drift loop with 2-3 angles. Fix the NaN ridge math (guard against invalid vertices). Budget: menu scene only, < 150k tris.'],
  ['F2-menu-muzik', 'SCOPE: new Infrastructure/Audio/Music/** only (other Audio files are off-limits) + one null-safe hook line in the main menu bootstrap (grep where the menu scene initializes; if that file is owned elsewhere, ENTEGRASYON line). Procedural menu music system: compose a Turkish-military-flavored ambient theme in code via layered synthesis (ProceduralAudioSynth API read-only — own synth helpers in Music/): low sustained strings-like pad (minor key, e.g. A minor), sparse deep davul-like percussion, a slow heroic melody line (ney/horn-like timbre via filtered saw + vibrato), subtle wind ambience; 60-90 s seamless loop generated once at first menu load and cached to persistentDataPath; volume follows GameSettings.MusicVolume (grep; add the setting + mixer route if missing via public API). Also: tense 20 s match-start sting and victory/defeat stings (hook via GameSession events, ENTEGRASYON lines if files owned). Pure note/pattern logic in a testable MusicScore class + EditMode tests.'],
  ['F3-nisan-hata', 'SCOPE: Presentation/UI/CrosshairView.cs, HitFeedbackDirector.cs, Presentation/UI/Hud/GrenadeWarningView.cs, DamageIndicator/DamageDirectionView (grep exact names), Presentation/Player/SuppressionDriver.cs + Suppression.cs (visual thresholds only). BUG (owner screenshot/report): when aiming (ADS), TWO VERY LARGE RED shapes appear on screen. Find and fix the cause: reproduce logically by reading every code path that draws red UI on/near ADS — candidate suspects: hit markers scaled by screen size, damage direction indicators triggering without damage, grenade warning icon mis-anchored/giant, suppression vignette drawing opaque red quads, crosshair kill-X stuck visible, lean arrows. Check RectTransform sizing (sizeDelta vs anchors — a stretched anchor plus big sizeDelta makes giant shapes), default-visible flags, and Update order that leaves views enabled with garbage data. Fix ALL of them: correct sizes (hit marker ≤ 32 px, indicators ≤ 120 px arc), hidden-by-default, show only on real events, fade-outs. Add EditMode tests for the pure sizing/visibility rules. Also sweep these files for other visual bugs (overlapping anchors, missing null checks).'],
  ['F4-karakter-gorunum', 'SCOPE: Infrastructure/Characters/CharacterMeshes*.cs, SoldierModel.cs + partials EXCEPT SoldierLook.cs and SoldierModel.Lean.cs. Owner: "characters look very bad". Improve the procedural soldier silhouette to believable human proportions: head size ~0.235 m with proper skull/jaw shape (not a box/sphere), neck, shoulder slope, chest/waist taper, correct arm segment ratios (upper 0.28/fore 0.26 m), hands at mid-thigh when relaxed, leg shape with calf/thigh taper, stance with slight knee bend and natural A-pose→idle, helmet sitting ON the head (not floating/clipping) with chin strap, vest conforming to torso, boots with ankle definition. Smooth-shaded normals everywhere (no faceted limbs), consistent skin/uniform material usage from MaterialLibrary. Keep bone names, hitboxes, ragdoll attachment points and all public APIs unchanged (RagdollRig reads these — verify by grep). Tri budget ≤ 7k. Update SoldierDetailRules tests only if proportions constants are asserted.'],
  ['F5-hata-tarama', `SCOPE: the specific files containing runtime errors + Logs analysis. Read ${ROOT}/Logs/claude/*.log (grep "error|Exception|abnormal|warning" summaries) and the game's Player.log at ~/Library/Logs/FPSGameStudio/HAREKÂT/Player.log. Known: (1) "Camera.layerCullSpherical only with built-in renderer" warning — find the caller, use URP-safe alternative; (2) [Diagnostics] client-errors HTTP spam "Cannot connect to localhost:5081" every few seconds — find the diagnostics/telemetry sender (grep 5081) and make it back off exponentially + disable when no backend configured; (3) any remaining NullReference/ArgumentException sources in Player.log (GrassInstance is already fixed; verify no other per-frame throwers). (4) Mesh NaN guards: add a shared MeshBuilder validation helper (NaN/inf vertex check with warning + skip) and call it in builders that produced "abnormal mesh bounds". Fix each at the source. Do not touch files other agents own for non-error work.`],
  ['F6-saha-detay', 'SCOPE: Infrastructure/World/TerrainGenerator.cs, TerrainPainter.cs, VegetationPainter.cs, World/FieldDetail*.cs (new). PUBG-style readable terrain at player level: farmland patches near villages (plowed row texture direction, crop stubble detail meshes), field boundary lines (low stone walls / bush rows along layout field edges), dirt road wear (center grass strip on side roads, tire ruts via existing road mask), scattered hay bales + rock piles as props (PropFactory public API or override ids), meadow flower patches only off-path, trampled grass circle around settlements, subtle terrain color noise at 50-200 m scale to kill uniformity. Deterministic by seed; generation time budget +%10 max; respects NavMesh (props with colliders registered like existing props).'],
  ['F7-bolge-duvari', 'SCOPE: new Infrastructure/Combat/ZoneWallVisual*.cs + zone visual code (grep how the zone circle is drawn today — likely a ring mesh/line). PUBG-style zone wall: translucent vertical energy wall mesh at the zone boundary (cylinder band 60 m tall, gradient alpha top/bottom fade, subtle scrolling hex/noise pattern via UV offset on an unlit transparent material, HDR blue tint — readable but not blinding), visible from both sides, follows zone shrink smoothly, next-zone preview ring on ground (thin white), damage side tint red beyond wall when outside, performance: single mesh 128 segments, no per-frame allocs, tier 0 falls back to the current simple ring. EditMode tests for the pure geometry (segment positions, shrink interpolation).'],
]
phase('G14a')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G14a', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
