export const meta = {
  name: 'harekat-feel-g8',
  description: 'HAREKÂT his dalgası G8: ragdoll + isabet tepkileri, prosedürel reload/inspect animasyonları, baskı (suppression) efekti, Tarkov tarzı dürbün (PiP, nefes tutma, sıfırlama), küçük his düzeltmeleri (5 Sonnet ajanı)',
  phases: [{ title: 'G8 His', detail: '5 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${ROOT}/Tools/UnityVerify/out_g8_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 URP C# at ${ROOT}. Owner target: Tarkov weapon feel + CoD MW combat feedback, realistic. Read only what you need (grep first).
Verify with ${V(id)} — 0 errors in your files, tests passing. A parallel agent (I4) is editing Infrastructure/Audio/**, Presentation/Player/PlayerWeaponHandler*.cs, Infrastructure/AI/BotController.Combat.cs, Combat/BallisticsSystem.cs, Combat/ExplosionSystem.cs — DO NOT edit those; if you need a call from them, expose a static entry point and write "ENTEGRASYON: <file>: <call>" in concerns. The 5 G8 agents have disjoint scopes listed per task — stay inside yours.
Golden rule: procedural fallback always works; override (humanoid/Animator) paths must keep working. Per quality tier (0..3) costs. No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. Turkish UI strings. Pure math in testable classes + EditMode tests (NUnit shim: no Assert.That/CollectionAssert). Append one dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük".`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['R1-ragdoll-tepki', 'SCOPE: Infrastructure/Characters/** (+ new Characters/Ragdoll*.cs, HitReaction*.cs). Ragdoll deaths: build a ragdoll from the procedural SoldierModel bone hierarchy (Rigidbody + CapsuleCollider/BoxCollider + CharacterJoint with sane limits per joint, mass distribution), on death switch from animation to ragdoll with impulse from the killing hit (direction, force by caliber/explosion), weapon drops as physics prop; humanoid override path uses existing EnterRagdollMode/GetHumanoidBone hooks; ragdoll pool / max active per tier (2/6/12/20), settle-detect then freeze to static + disable colliders after 6 s; ragdoll layer must not block bullets/NavMesh incorrectly; downed (yaralı) state does NOT ragdoll. Hit reactions: additive procedural flinch per body region (head snap, shoulder twist, leg buckle), stagger on heavy hits/explosions, directional. Expose SoldierModel.PlayHit(region, dir, strength) + SoldierModel.Die(hitDir, force) if not present (check existing PlayDeath API and keep it working). Tests for pure joint-limit/impulse math.'],
  ['R3-reload-animasyon', 'SCOPE: Infrastructure/Weapons/WeaponViewModel*.cs (new partial WeaponViewModel.Reload.cs / .Inspect.cs) + new pure Core/Application ViewmodelPoseTimeline. Procedural keyed viewmodel animations (CoD/Tarkov quality motion curves, overshoot, anticipation): reload per weapon category (rifle box mag: tilt, mag out drop, left hand to pouch, mag in, slap, charging handle/bolt for empty; MG belt: top cover open, belt, close; pistol: mag out, in, slide release; bolt-action: bolt cycle per round; shotgun: shell-by-shell with interrupt), timings matched to the foley step plan in Infrastructure/Audio/Foley/FoleyLogic.cs (READ it, do not edit) and to weapon ReloadDurationSeconds; empty vs tactical; weapon inspect (key from InputBindings — add BindAction.Inspect if missing, default V... check conflicts in Docs/KONTROLLER.md and pick a free key), equip/holster draw anims, sprint pose (tactical sprint on double-tap optional), fire mode switch thumb motion, dry-fire. The left-hand mag object must visibly detach (procedural magazine child). Expose WeaponViewModel.PlayReload(empty, duration) etc. matching what PlayerWeaponHandler already calls (grep) — keep signatures backward compatible.'],
  ['R4-baski-efekti', 'SCOPE: new Presentation/Player/Suppression*.cs + new Infrastructure/Rendering/CombatScreenFx*.cs (do not edit PostProcessing.cs; use its public API or a separate local Volume with high priority). Suppression system like Battlefield/Tarkov: near-miss bullets (Suppression.ReportNearMiss(point, caliber, distance)), nearby explosions, incoming MG fire build a 0..1 suppression value with decay; effects: vignette darkening, slight desaturation, chromatic edge, brief blur, increased weapon sway multiplier (expose Suppression.SwayMultiplier for viewmodel/aim code), small camera shake; low-health effects: red-tinted vignette pulse, desaturation; explosion concussion visuals (white flash + blur ramp) synced with tinnitus snapshot if AudioMix exposes state (read-only). Player-only, local. Settings slider for intensity (reuse GameSettings.CameraShakeIntensity or add a separate PlayerPrefs key). ENTEGRASYON lines for Acoustics.OnBulletPassed (I4 area) and explosion code.'],
  ['R7-durbun', 'SCOPE: new Infrastructure/Weapons/Scope*.cs + Presentation/Player/ScopeInput*.cs (do not edit PlayerWeaponHandler; expose hooks). Tarkov-style optics: picture-in-picture magnified scope on Yüksek/Ultra (second camera rendering to RenderTexture on the lens material, reduced FOV by magnification, culling of viewmodel layer), cheap fallback on Düşük/Orta (full-screen zoom + scope overlay vignette); scope shadow/eye-box (dark ring that shifts with sway/misalignment); reticle per sight (red dot, ACOG-style 4x chevron, sniper mil-dot with zeroing); hold breath for scoped weapons (key Shift while ADS — check conflicts; stamina-limited 4 s, then shake), variable zoom on mouse wheel for variable scopes, zeroing 100/200/300/400/500 m (PageUp/PageDown) affecting bullet origin angle (expose Scope.ZeroingAngle(weaponId) for ballistics — ENTEGRASYON line), scope glint visible to enemies at distance (sprite billboard facing toward sun-ish), lens dirt/reflection. Pure ScopeMath (fov from magnification, zeroing angle with gravity + muzzle velocity) + tests.'],
  ['R6-kucuk-his', 'SCOPE: Infrastructure/Rendering/CameraRig.cs, Presentation/Player/PlayerController*.cs (camera only, not spawn/grass lines), Presentation/UI/SettingsPanel.cs, Core GameSettings (+SettingsService if needed), Presentation/Bootstrap/HostageBootstrap.cs. Do: (1) enable CameraRig camera kick (CameraKickEnabled) correctly — make the player look controller apply kick additively so it does not fight absolute rotation writes; recoil pattern recovery feel; (2) viewmodel FOV setting (GameSettings.ViewmodelFov 50–80, default 60) wired to CameraRig.SetViewmodelFieldOfView + settings slider "Silah görüş açısı"; (3) volumetric fog + contact shadows + SSR user toggles in SettingsPanel (QualityTierApplier.SetVolumetricUser, HarekatRendererFeatures.SetUserEnabled); (4) HostageBootstrap: BootstrapUtility.InstallGrass(...) like the others; (5) mouse/FOV-relative ADS sensitivity option (Tarkov/CoD style "ADS hassasiyet çarpanı"). Keep settings save/load backward compatible.'],
]
phase('G8 His')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G8 His', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
