export const meta = {
  name: 'harekat-feel-6',
  description: 'HAREKÂT dalga 6 oyun hissi: AI taktikleri, silah hissi, mermi delme, bastırma geri bildirimi, ses kalitesi, animasyon (6 Sonnet ajanı)',
  phases: [{ title: 'Dalga 6', detail: '6 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${ROOT}/Tools/UnityVerify/out_${n} --player --tests`
const RULES = `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6 C# at ${ROOT}. Editor can't run here; verify with ${V('<name>')} — keep 0 errors, all tests passing (489).
Read ${ROOT}/ARCHITECTURE.md sections you need. TOKEN-EFFICIENT: open only needed files (grep). Prefer NEW files in your scope; small null-safe edits elsewhere.
No deletes/.meta/file-changing git. UnityEngine.Application inside Project.* namespaces. Turkish UI. Procedural content. Add EditMode tests for pure logic
(tests that need Infrastructure/Presentation must be wrapped in #if UNITY_EDITOR). Cursor is concurrently fixing real-Unity errors anywhere; 7 other Claude agents run in parallel —
stay strictly in your scope.  Append a dated line to ${ROOT}/Docs/DURUM.md "Günlük" when done.`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const F = [
  ['ai-taktik', `Scope Infrastructure/AI/* only. Deeper squad tactics: cover selection (score nearby structure/rock/ terrain-dip points by LOS to enemy + distance), flanking (one fire team suppresses while another moves around at 30–60° offset), suppressive fire (bots fire at last known position when target hides), bounding overwatch when advancing, better grenade use (enemy behind cover within 25 m, not near allies), retreat to heal when <35% and under fire. Keep 60-bot perf (reuse BotLod tiers, staggered work, no allocations). Pure helpers with tests where possible.`],
  ['silah-his', `Scope Application/Catalogs/WeaponCatalog.cs, Application/Services/WeaponRuntimeService.cs (+ new Application/Services/RecoilPattern.cs), Presentation/Player/PlayerWeaponHandler.cs. Call-of-Duty-like gun feel: deterministic per-weapon recoil patterns (first 10–15 shots learnable, then random), first-shot accuracy bonus, ADS transition time (spread & zoom blend over Definition.AdsTime), hold-breath on scoped weapons (Shift while scoped: 4 s steady, then sway penalty), weapon-specific recoil recovery. Tests for RecoilPattern and ADS blend.`],
  ['mermi-delme', `Scope Infrastructure/Combat/BallisticsSystem.cs (+ new Infrastructure/Combat/Penetration.cs, Application pure PenetrationRules.cs with tests). Bullet penetration: through wood/plaster/thin metal/foliage with thickness check (back-face raycast), damage & velocity reduction by caliber (7.62 > 5.56 > 9mm > 12ga pellets), no penetration of concrete/stone/terrain; ricochet chance at shallow angles on metal/concrete with spark + whine; use GameVfx.Classify surface kinds. Keep per-frame cost bounded.`],
  ['bastirma', `Scope NEW Presentation/UI/Suppression*.cs, HitFeedback*.cs, Infrastructure/Rendering/ScreenEffects*.cs + small edits in Infrastructure/Player/FirstPersonCameraController.cs. Suppression: near-miss bullets (BallisticsSystem whiz event — add a tiny static event if missing) raise a suppression meter → vignette/desaturation + slight aim sway; low health: heartbeat loop + red edge + muffled audio (AudioLowPassFilter on listener via GameAudio API if present); hit feedback: directional camera punch on taking damage, hitmarker sounds by body part (headshot ding), kill confirm stinger. Do not edit PlayerWeaponHandler.`],
  ['ses-kalite', `Scope Infrastructure/Audio/* (+ one small hook in Infrastructure/World/BuildingGenerator.cs to add AudioReverbZone inside buildings). Higher-quality procedural audio: gunshot layering (mechanical click + body + tail), distance variants (close/mid/far crack-thump with delay), indoor reverb vs outdoor echo, per-surface footsteps (dirt/grass/concrete/wood/metal via GameVfx.Classify or terrain splat), cloth/gear rustle while moving, reload sounds per weapon class, shell casing tinkles. Keep generation < 400 ms total and cache.`],
  ['animasyon', `Scope Infrastructure/Weapons/* (viewmodel) and Infrastructure/Characters/* (third-person). Animation polish: weapon inspect (key from InputBindings if exists else 'I' with alt? — use F4? no: add binding "Inspect" default Key.K in InputBindings via small edit), per-class reload phases (mag out/in, bolt, belt for PMT-76, shell insert for Escort), sprint pose & transition, landing dip, smoother ADS curve, idle breathing; third-person: aim offset for pitch, crouch/prone walk cycles, reload & throw gestures, hit flinch, smoother death fall. Keep procedural (no assets).`],
]
phase('Dalga 6')
const out = await parallel(F.map(([k, task]) => () => agent(`${RULES}\nTASK ${k}: ${task}`, { label: k, phase: 'Dalga 6', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
