export const meta = {
  name: 'harekat-fixround-g20',
  description: 'HAREKÂT G20 kare-kanıtlı düzeltme: kayıp silah/override doğrulama, lobi asker teçhizat + alev şekli, vitrin silah karesi, harita çekim modu, ağaç parlaklık/uzak toplar (5 Sonnet ajanı)',
  phases: [{ title: 'G20', detail: '5 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const MENU = `${ROOT}/Logs/otoekran/menu/menu_2.png`
const GUN = `${ROOT}/Logs/otoekran/bench2/01_silah_yakin_plan.png`
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g20_${n} --player --tests`
const RULES = (id, img) => `Project HAREKÂT, Unity 6000.6.4 URP C# at ${ROOT}, Turkish UI. FIRST ACTION: Read the screenshot ${img} — your task fixes a defect visible in it. 5 parallel agents, disjoint scopes; cross-file → "ENTEGRASYON" concern; grep APIs first.
Do NOT launch Unity. Verify with ${V(id)} (0 errors; tests ~1696 passing). No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. Dated Turkish line to Docs/DURUM.md.`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['R1-silah-kayip', GUN, `SCOPE: Infrastructure/Weapons/WeaponModelFactory.cs (override path), Editor/ThirdParty/ThirdPartyWeaponBinder.cs. DEFECT: since the Quaternius weapon overrides were bound, weapons are INVISIBLE everywhere (menu soldier holds nothing; benchmark gun shot empty). Root-cause candidates: override prefab instantiated with broken scale/orientation/materials, renderers disabled, pivot far from hand so mesh is meters away, or prefab load returns an empty object. Fix BOTH sides: (1) WeaponModelFactory: after instantiating an override, VALIDATE it — at least one enabled Renderer whose combined bounds size is 0.1–2.0 m and bounds center within 1 m of the root; otherwise Destroy it, log one warning with weaponId, and build the PROCEDURAL model instead (never leave an empty hand); (2) ThirdPartyWeaponBinder: re-check the generated prefabs — material assignment (FBX submeshes may need the URP/Lit material on every renderer; Quaternius models often import with missing materials → magenta or none), scale heuristic result sanity (log each model's final bounds), pivot placement at Grip_R, and WRITE the computed bounds into the prefab name metadata log so the next SetupAll prints them. If a model cannot be made sane, drop its override entry (procedural is better than invisible).`],
  ['R2-lobi-techizat', MENU, `SCOPE: Presentation/UI/MenuBackdropDiorama.cs, MenuBackdropLook.cs, MenuCampfire.cs, MenuSceneMath.cs. DEFECTS in the menu shot: (1) the soldier is BALD and bare — no helmet/beret visible, vest reads as floating dark boxes; use SoldierModel's equipment API correctly (grep SetEquipment/helmet levels; give kask seviye 2 + yelek + sırt çantası; verify attach succeeds in menu context — catalogs/GameContext init first if the API needs it, null-safe); (2) rifle missing in hands: build it via WeaponModelFactory with catalog init; if the factory returns an invisible model (R1 fixes the validator), the procedural fallback must appear; position at low-ready; (3) campfire flames are TALL VERTICAL SPIKES (looks like glowing spears): flame cards must be max 0.45 m tall, wider than tall at the base (aspect ~0.8w:1.0h), rounded teardrop mask (fix MenuSceneMath.FlameMask), flicker ±15% not full-length stretch; (4) add soft contact shadow blob under soldier and props (dark transparent quad); (5) soldier pose: slight weight shift, head looking toward camera-left (not T-pose arms).`],
  ['R3-vitrin-silah', GUN, `SCOPE: Presentation/Benchmark/** only. DEFECT: Vitrin "01_silah_yakin_plan" frame contains NO gun and NO shooter — just terrain. The shot must be an over-the-shoulder view of the benchmark soldier aiming the MPT-76 at targets. Debug the chain in code: does AaaBenchmarkBootstrap actually spawn the player/soldier with a weapon in Vitrin mode (grep how the player rig is created; OtoEkran runs without normal input/player spawn maybe)? Ensure: a posed soldier with rifle exists for shots 1-2-6 (spawn a dedicated "vitrin askeri" SoldierModel + weapon if the player rig is absent), camera positions relative to that soldier, muzzle flash + tracer triggered during shot 6 via GameVfx so the firing frame shows action. Keep Oyna mode untouched.`],
  ['R4-harita-cekim', GUN, `SCOPE: Presentation/Bootstrap/OtoEkranRunner.cs, OtoEkranArgs.cs, OtoEkranViewpoints.cs. DEFECT: "-otoekran-harita KuzgunVadisi <dir>" does nothing — player.log shows the game stayed on the main menu (no [OTOEKRAN] line at all). Root-cause: the map mode's Bootstrap gate or scene-name mismatch (grep SceneNames; the scene file is KuzgunVadisi.unity; maybe TryParse fails on the two-arg flag order, or the runner waits for a world that never generates because the map scene expects MatchBootstrap flow). Fix: parse robustly (log the parsed options ALWAYS, even on failure log why), load the scene additively or via the normal flow with bots disabled (BotRuntimeGate), wait for terrain (Terrain.activeTerrain != null) with 60 s cap, then 5 viewpoints from WorldMetadata (fallback: terrain-bounds-derived points at height+2 m looking at terrain center), capture, quit. Make it log every step "[OTOEKRAN] adım: ...".`],
  ['R5-agac-parlaklik', GUN, `SCOPE: Infrastructure/World/VegetationTextures.cs, VegetationMaterials.cs, TreeMeshes.cs (LOD/billboard color only), WorldAssetPersistence.cs (stale prototype check). DEFECTS in the frame: (1) pine needles render nearly BLACK in daylight (silhouettes OK but should be dark olive-green with sunlit side clearly green — likely texture too dark + translucency not applied on the shadow side; brighten needle albedo ~1.6x, raise shaded-vertex AO floor to ~0.72, ensure material tint near-white and translucency reaches the URP Lit path fallback via emission-free wrap or baked brightness); (2) the distant trees at center-left horizon are still old LIGHT-GREEN BLOBS — probable stale persisted tree prototypes in Assets/_Project/Generated/** (WorldAssetPersistence may reuse old LOD meshes instead of regenerating; add a version stamp to persisted tree prototype assets and regenerate when the mesh version changes — bump version now); (3) tree shadows look good — don't touch lighting.`],
]
phase('G20')
const out = await parallel(T.map(([id, img, task]) => () => agent(`${RULES(id, img)}\nTASK ${id}: ${task}`, { label: id, phase: 'G20', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
