export const meta = {
  name: 'harekat-gameplay-g11',
  description: 'HAREKÂT oynanış dalgası G11: gerçekçi bot taktikleri, silah dengesi/tepme desenleri, hareket hissi (atalet/eğilme/dayanıklılık), maç akışı (loot/bölge/temas temposu) (4 Sonnet ajanı)',
  phases: [{ title: 'G11 Oynanış', detail: '4 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g11_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR: 10-person timler, rütbeler, T-70/Kirpi intikal, Türk silahları), Unity 6000.6.4 C# at ${ROOT}. Owner's main goal: make the GAME itself much better — fun, tense, realistic (Tarkov/PUBG/CoD-MW feel). First read the relevant existing systems (grep; ARCHITECTURE.md, Docs/CONTRACTS.md sections) and IMPROVE them; don't rebuild from scratch. Server-authoritative design must hold (simulation in Application/Infrastructure, PlayerCommand/ShotRequest path unchanged in shape).
PARALLEL: graphics waves are editing Rendering/**, Shaders/**, Characters/** materials, Weapons/** model materials, World/BuildingGenerator*, World/Terrain*, Assets/ThirdParty/**, Editor/ThirdParty/**, Editor/BatchEntry.cs, Presentation/Benchmark/**, Bootstrap arg parsing, Resources/Audio/**. The 4 G11 agents have disjoint scopes per task. Use "ENTEGRASYON: <file>: <call>" in concerns for anything outside your scope.
Do NOT launch Unity. Verify with ${V(id)} (0 errors, all tests passing — update tests only when the old expectation is genuinely superseded, and say so). Add EditMode tests for every rule change. No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. Turkish UI strings. Append a dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük" and document tunables in ${ROOT}/Docs/OYNANIS_REHBERI.md (append a section).`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['P1-bot-taktik', 'SCOPE: Infrastructure/AI/** (BotController*, BotTactics, BotPerception, BotDirector, BotBrain). Make bots fight like disciplined soldiers, not aimbots: use cover properly (cover scoring vs threat direction, peek-and-fire from cover, lean), bounding overwatch within a tim (one moves while others suppress), flanking when pinned, reaction to suppression (accuracy & willingness to peek drop under fire, crawl to cover), grenade usage to flush cover, retreat when outnumbered/low HP, revive teammates under smoke, communicate via existing radio callouts (RadioChatterSystem/DialogueDirector API), human-like aim (reaction time 180–450 ms by rank/skill, first-shot error that converges, recoil control imperfect, target-switch delay), hearing (footsteps/gunfire with distance & occlusion → investigate). Difficulty tiers. Keep BotLod performance budget (60 bots).'],
  ['P2-silah-denge', 'SCOPE: Application/Catalogs/WeaponCatalog.cs + AttachmentCatalog/AttachmentStats, Application/Services/RecoilPattern.cs, DamageCalculator.cs, WeaponRuntimeService.cs, PenetrationRules.cs (+ tests). Realistic yet fun gunplay balance for all 16 weapons: real-world-ish muzzle velocities, bullet drop & travel time per caliber (7.62x51, 5.56x45, 9x19, .338, 12ga), damage falloff curves, body-part multipliers, armor classes (kask/yelek seviyeleri) with penetration vs caliber, TTK targets (document table: e.g. MPT-76 3 body shots unarmored at <100 m), per-weapon deterministic recoil patterns (first 10 shots learnable + random component), recoil recovery, ADS times by weight, sprint-to-fire time, attachment trade-offs. Produce Docs/SILAH_DENGESI.md with the final table. Keep WeaponIds/network indices stable.'],
  ['P3-hareket-hissi', 'SCOPE: Infrastructure/Player/** (CharacterControllerMotor*, FirstPersonCameraController), Presentation/Player/PlayerController.cs (movement parts only — not camera kick/scope/grass lines), Application stamina/movement rules. Movement like Tarkov-lite/MW: acceleration & deceleration inertia (weight from loadout/armor), stamina (sprint drain, regen delay, breathing audio hook ENTEGRASYON), jump/landing stamina cost, slope speed modifiers, crouch-walk / prone crawl speeds, smooth stance transitions with camera height curves, lean (Q/E) with collision check, mantle/vault polish, footstep cadence tied to speed (ENTEGRASYON for audio), slide limited. Keep network PlayerCommand compatible.'],
  ['P4-mac-akisi', 'SCOPE: Application/Services/MatchService.cs, LootSpawnService.cs, Zone rules (grep ZoneService/ZoneRules), MatchConfig, Infrastructure loot spawners (not PropFactory), BotDirector match-level pacing ONLY if not touched by P1 (else ENTEGRASYON). BR flow tuning: loot distribution by location tier (military base > village > field), guaranteed minimum kit near insertion, zone timings and damage per phase for a 1 km map with 6×10 players, airdrop/supply crate events (T-70 drops a crate) with high-tier loot, mid-match events (artillery barrage zone already exists — tune), encounter pacing (avoid dead time > 90 s, avoid instant third-partying), end-game zone shapes that favor terrain. Produce Docs/MAC_AKISI.md with timeline table.'],
]
phase('G11 Oynanış')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G11 Oynanış', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
