export const meta = {
  name: 'harekat-graphics-10',
  description: 'HAREKÂT grafik dalgası 2: bitki örtüsü, su, gökyüzü, asker modeli, silah modeli detayı (5 Sonnet ajanı)',
  phases: [{ title: 'Grafik 2', detail: '5 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${ROOT}/Tools/UnityVerify/out_${n} --player --tests`
const RULES = `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6 C# at ${ROOT}. Editor can't run here; verify with ${V('<name>')} — keep 0 errors, all tests passing (737).
Read ${ROOT}/ARCHITECTURE.md sections you need. TOKEN-EFFICIENT: open only needed files (grep). Prefer NEW files in your scope; small null-safe edits elsewhere.
No deletes/.meta/file-changing git. UnityEngine.Application inside Project.* namespaces. Turkish UI. Procedural content. Add EditMode tests for pure logic
(tests that need Infrastructure/Presentation must be wrapped in #if UNITY_EDITOR). Cursor may concurrently fix real-Unity errors anywhere; 12 other Claude agents run in parallel (wave 9 owns: Replay*, FlyableHelicopter, Transport/*, Support/*, MapLayoutKartalYaylasi + PropFactory appends, SeasonPass*, Destructible + BuildingGenerator/PropFactory destructible hooks, Training challenges, AimAssist/SettingsPanel) —
stay strictly in your scope.  Append a dated line to ${ROOT}/Docs/DURUM.md "Günlük" when done.`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const F = [
  ['bitki', `Vegetation quality: Infrastructure/World/TreeScatter.cs, MeshFactory.cs (tree/bush/rock meshes), TerrainGenerator.cs (detail layers). Higher-detail procedural pine (layered drooping branch cards with alpha-cutout needle texture generated procedurally), oak (multi-lobe canopy with leaf-card clusters), bushes, dead trees; 3 LOD levels + billboard; terrain DETAIL grass (procedural grass blade texture, detail prototypes painted by layer: grass/dry grass/flowers on plateau, none on roads/rock/snow) with density per quality tier; rocks with more facets and moss tint on top; wind: use terrain wind settings (wavingGrass*) and a subtle vertex-sway via a shared material property block-free approach (or Terrain tree wind if supported). Keep perf budget (density tiers).`],
  ['su-gokyuzu', `Water & sky: Infrastructure/World/WorldWater.cs + new Infrastructure/Rendering/WaterSurface*.cs, Sky*.cs. Water: animated normal-mapped surface (two scrolling procedural normal maps), depth-based color via simple shoreline foam strip mesh along lake/river/sea edges, fresnel-ish smoothness, underwater fog tint when camera below water level. Sky: improved procedural skybox params per time of day + cloud layer (large dome mesh with scrolling procedural cloud texture, alpha), sun disk/halo, distant mountain silhouette ring for horizon depth, light shafts billboards at dawn/dusk (cheap). Integrate with Atmosphere presets (read-only API; add one hook call if needed).`],
  ['asker-model', `Soldier model detail (procedural): Infrastructure/Characters/*. Higher-fidelity body (beveled/tapered limb meshes instead of boxes, shaped torso, hands with fingers block-out), TSK-style gear: plate carrier with pouches, helmet with cover + NVG mount, knee pads, gloves, boots, radio antenna for Radioman, medic armband, backpack variants, beret for leader; camo via ProceduralTextures digital camo with normal map; face with simple features + balaclava/shemagh variants per team; better procedural animation blending (hip sway, arm swing, weapon carry poses). Keep hitbox placement aligned. Triangle budget ~3–5k per soldier.`],
  ['silah-model', `Weapon model detail: Infrastructure/Weapons/* model builders (WeaponBlueprints*, WeaponModel*, mesh builders) — NOT WeaponViewModel animation logic. Add beveled receivers, rails with slots, magazine curvature, muzzle devices (flash hider/compensator per weapon), sights (iron, red dot glass with emissive dot, scope lenses with dark glass), stock details, trigger guard, bolt handle, belt feed tray for PMT-76/MG3, wood grain for G3A7 option; PBR materials (gun metal normal/mask from ProceduralPbr). Viewmodel arms: sleeves with camo + gloves with fingers. Triangle budget ~6–10k per viewmodel weapon, 1–2k for world/loot LOD.`],
  ['arac-model', `Vehicle model detail: Infrastructure/Vehicles/KirpiModelBuilder.cs, CobraModelBuilder.cs, Infrastructure/Transport visual model builders (HelicopterModel/KirpiModel for insertion) — coordinate: do NOT edit FlyableHelicopter (wave 9). Add beveled armor plates, wheel rims + tire treads, mirrors, lights (emissive), windows with frames, turret shield, antennas, tow hooks, number plates/insignia (TSK-like stylized, original), helicopter: refined fuselage, cockpit glass, rotor hub detail, sponsons, rotor blur disc at speed. Keep colliders/seats untouched.`],
]
phase('Grafik 2')
const out = await parallel(F.map(([k, task]) => () => agent(`${RULES}\nTASK ${k}: ${task}`, { label: k, phase: 'Grafik 2', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
