export const meta = {
  name: 'harekat-graphics-g10',
  description: 'HAREKÂT grafik dalgası G10: oto pozlama + fiziksel ışık, AA/keskinlik, karakter ve silah materyalleri, bina yıpranma, arazi erozyon/kayalık, bulut gölgeleri + atmosfer detay, zemin/duvar decal serpme (8 Sonnet ajanı)',
  phases: [{ title: 'G10 Grafik', detail: '8 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g10_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 URP 17.6 C# at ${ROOT}. Target look: photoreal like Tarkov / Sons of the Forest / CoD MW2019 — believable light, materials and weathering. Context: Docs/GERCEKCILIK_PLANI.md, Docs/AAA_URP_20.md (skim only the relevant parts).
The project already has: QualityTierApplier (single tier apply point), HarekatRendererFeatures framework (Rendering/Features), VolumetricFog, contact shadows, SSR-lite, PostProcessing grade presets, Atmosphere + SkyEnvironment, MaterialLibrary + MaterialSpec + ProceduralPbr, TerrainShaderBinder, GrassSystem, WindSystem, DecalPool, ContentOverrides. Grep and REUSE them; register new renderer features through HarekatRendererFeatures and new tier knobs through QualityTierApplier.
Shaders go under Assets/_Project/Shaders/<Area>/ named "HAREKAT/..."; write carefully for URP 17.6 (use half literals like 1.0h not 1h; no HLSL-invalid syntax); Shader.Find fallback = current path + one warning. The orchestrator builds in real Unity and reads shader errors from the build log, then fixes them.
PARALLEL: another wave (G9) is editing Assets/ThirdParty/**, Editor/ThirdParty/**, Editor/BatchEntry.cs, Presentation/Benchmark/**, Presentation/Bootstrap/** arg parsing, Resources/Audio/**, and scatter call sites in TreeScatter/RockScatter/PropFactory (override lookups) — don't edit those. The 8 G10 agents have disjoint scopes given per task; stay inside yours and use "ENTEGRASYON: <file>: <call>" in concerns for anything outside.
Do NOT launch Unity. Verify C# with ${V(id)} (0 errors, tests passing). Pure math in testable classes + EditMode tests. No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. Append a "## ${id}" section to ${ROOT}/Docs/AAA_URP_20.md and one dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük".`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['GX1-isik-pozlama', 'SCOPE: new Rendering/Features/AutoExposure*.cs + Shaders/PostFx/AutoExposure*.shader, Rendering/Atmosphere.cs (sun/ambient values only), Core LightingMath (new). Eye adaptation: renderer feature that downsamples scene luminance (log-average via mip chain or 64x64 reduction), smooth adaptation up/down speeds (dark→bright fast, bright→dark slow), clamps per map, feeding a global exposure applied in a cheap final pass (or via ColorAdjustments.postExposure override if simpler & robust). Physically-motivated sun: color temperature + intensity curve by sun elevation (Kelvin 2000 at horizon → 5800 noon), ambient from sky (trilight gradient or HDRI SH if SkyOverride present), indirect boost in shade for interiors (consistent with probes), shadow strength by weather. Make interiors read dark and exteriors bright like real cameras.'],
  ['GX2-aa-keskinlik', 'SCOPE: Rendering/CameraRig.cs (AA + camera settings only), new Rendering/Features/Sharpen*.cs + Shaders/PostFx/CasSharpen.shader, PipelineTiers.cs (AA columns only). Per tier anti-aliasing: Düşük FXAA, Orta SMAA High, Yüksek TAA (quality high) or STP when STP is the upscaler, Ultra TAA/STP + higher render scale; viewmodel/overlay camera AA consistent (no smearing on the gun: TAA jitter on overlay camera handled — if overlay stacking breaks TAA, keep the gun crisp via base-camera AA settings and document). AMD CAS-style contrast-adaptive sharpening pass after TAA (strength per tier + user slider key "Keskinlik" stored in PlayerPrefs; SettingsPanel ENTEGRASYON line). Mip bias for textures under TAA/STP (negative lod bias ~ -0.5 via QualitySettings or texture setting when render scale < 1).'],
  ['GX3-karakter-materyal', 'SCOPE: Infrastructure/Characters/** materials only + new Shaders/Character/*.shader. Realistic soldier materials: fabric shader (cloth sheen/rim, fuzz, camo detail normal tiled + macro dirt/mud gradient at boots/knees, wetness under rain via _HarekatWetness), skin shader (wrap-diffuse + subsurface tint, pore detail normal, specular occlusion), hard gear (helmet painted matte w/ edge wear, plate carrier cordura, rubber, metal buckles), NVG lenses. Procedural textures generated once and cached (ProceduralTextures/ProceduralPbr helpers). Keep override (humanoid) path untouched; procedural soldier uses these materials; fallback URP/Lit.'],
  ['GX4-silah-materyal', 'SCOPE: Infrastructure/Weapons/** model materials only (not WeaponViewModel motion/reload) + new Shaders/Weapon/*.shader. Gun materials like Tarkov/MW: parkerized steel and anodized aluminum with edge wear (curvature-like wear from mesh bevel UVs or vertex color masks written by the procedural builders), polymer with micro texture, wood grain (G3), worn paint, oil sheen; glass of optics with tinted coating + reflection; muzzle carbon buildup darkening after firing (material property per weapon increasing with shots, cleaning over time). Viewmodel lighting: make the gun pick up environment reflections (reflection probe at camera / SH) so it is not flat in interiors; avoid overly dark viewmodel.'],
  ['GX5-bina-yipranma', 'SCOPE: Infrastructure/World/BuildingGenerator*.cs and new World/BuildingWeathering*.cs (+ Shaders/Surface/HarekatWeatheredWall.shader optional). Anatolian village realism: plaster walls with damaged patches revealing stone/brick (secondary material via vertex color mask or second submesh), rising damp / dirt gradient at wall base, rain streaks under windows/roof edges, roof overhang with visible wooden eaves, clay tile roofs with ridge tiles, window frames (wood) with recessed glass + interior darkness, door frames + steps, chimney, satellite dish/antenna on some, electricity poles and sagging cables between houses, laundry lines, interior basics (floor material, rug, table, bed boxes) for enterable houses. Keep colliders, NavMesh-relevant geometry and destructible windows (Destructible) intact.'],
  ['GX6-arazi-erozyon', 'SCOPE: Infrastructure/World/TerrainGenerator.cs, TerrainPainter.cs, TerrainTextureFactory.cs, TerrainPaintRules*, new World/TerrainErosion*.cs. Realistic mountain terrain: hydraulic + thermal erosion pass on the heightmap (fast, bounded iterations, deterministic seed; quality-safe for 1 km maps; budget < 2 s at generation), flow/wetness map → gullies get mud/gravel, ridges get rock; slope-based rock outcrops (spawn rock clusters on steep cliffs via RockScatter public API — read only — or list ENTEGRASYON), scree at cliff bases, curvature-based ambient darkening baked into a colormap; distance colormap/macro tint to break tiling at 200 m+; road edge blending (soft transitions + tire-rut darkening). Keep layouts (settlements/roads) flat where they were and keep determinism (tests).'],
  ['GX7-bulut-golge-atmosfer', 'SCOPE: new Rendering/CloudShadows*.cs, new Rendering/AtmosphereDetail*.cs, SkyEnvironment.cs (small hooks). Cloud shadows moving over the landscape (main light cookie texture: procedural tileable cloud noise, scrolled by wind direction from WindSystem; URP light cookie on directional light with size ~800 m; per-weather coverage; off on Düşük) — hugely important for realism on mountains. Dust motes / floating particles in sun shafts near camera (very cheap, only when sun visible and VolumetricFog active), distant haze layers between mountain ridges, high-altitude cirrus layer, sun glare/lens flare (URP Lens Flare (SRP) component with a subtle flare asset generated in code if API allows; else a cheap sprite flare with occlusion raycast).'],
  ['GX8-decal-serpme', 'SCOPE: new Infrastructure/World/DecalScatter*.cs + Rendering/DecalLibrary*.cs (procedural decal textures generated in code: puddles, mud splats, tire tracks, fallen leaves/needles, oil stains, wall grime/soot streaks, moss patches, cracks, graffiti-free posters). Uses URP DecalProjector (check the project already enables the Decal renderer feature — UrpSetup); scatter rules: puddles in low flat spots near roads/village (more when wet), tire tracks along roads, leaves under trees, grime at wall bases and around windows, soot over chimneys, cracks on concrete; per-tier count limits + distance fade; deterministic by world seed. Expose DecalScatter.Run(worldRoot, layout, seed, tier) and list the ENTEGRASYON line for WorldGenerator/SceneBuilder.'],
]
phase('G10 Grafik')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G10 Grafik', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
