export const meta = {
  name: 'harekat-integ-g6',
  description: 'HAREKÂT entegrasyon G6: G3+G4 ENTEGRASYON kancalarını bağla (kalite/atmosfer merkezi, dünya/editör, oynanış kancaları) + test düzelt (3 Sonnet ajanı)',
  phases: [{ title: 'Entegrasyon', detail: '3 dosya-ayrık ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const NOTES = `${ROOT}/Tools/AgentWorkflows/notes`
const J3 = '/Users/f2gomac/.claude/projects/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/subagents/workflows/wf_99abe4ae-e5b/journal.jsonl'
const J4 = '/Users/f2gomac/.claude/projects/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/subagents/workflows/wf_5abcfa5a-d71/journal.jsonl'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${ROOT}/Tools/UnityVerify/out_g6_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT, Unity 6000.6.4 URP C# at ${ROOT}. Two waves (G3 realism C1–C15, G4 AAA URP S1–S8) just landed new systems that expose static entry points but are NOT called yet. Your job: wire the hooks in YOUR file set so the systems actually run, keeping every fallback safe (null checks, try/catch around reflection-y installs, no behavior change when shader/asset missing).
Hook lists: ${NOTES}/g3_concerns.txt and ${NOTES}/g4_concerns.txt (lines starting "ENTEGRASYON" and wiring notes). If a line is truncated, grep the full text in ${J3} or ${J4} (JSONL, one "type":"result" line per agent) — use grep -o with a short context, don't cat whole files. Always confirm the real API by grepping the target class before calling it.
A parallel audio wave (G5) is editing Infrastructure/Audio/** right now — DO NOT edit Audio files; compile errors coming from Audio/** are theirs, ignore them (if they block your verify, copy-check by reading errors only for your files).
Verify: ${V(id)} — 0 errors in your files; report test counts. No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. Append one dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük". Final answer: which hooks you wired (file:line), which you skipped and why.`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['I1-kalite-atmosfer', `FILES YOU OWN: Infrastructure/Rendering/PostProcessing.cs, PerformanceProfile.cs, RenderSettingsUtil.cs, Atmosphere.cs, SkyEnvironment.cs, Core AtmosphereMath / VolumetricFogMath (gate alignment only), + NEW Infrastructure/Rendering/QualityTierApplier.cs.
Create QualityTierApplier.Apply(int tier, Camera cam) as the ONE place that applies a quality tier: PerformanceProfile.ApplyPipeline, SsaoTuner, HarekatRendererFeatures.Install, VolumetricFog.Install(tier,userEnabled), TextureStreamingSetup.Install(cam,tier) (also HlodProxy tier), GrassSystem.SetTier, WindSystem.SetTier, GpuVfx.Tier, TerrainShaderBinder.Install for all active terrains, TerrainPaintRules.ApplyTier, PlanarReflection.Install(cam,tier). Call it from wherever the game currently applies quality on startup and on settings change (find it: grep PerformanceProfile.Apply / QualitySettings.SetQualityLevel / SettingsService apply in Rendering + Presentation/Bootstrap; adding ONE call line in a Presentation bootstrap/SettingsPanel apply path is allowed).
Create a weather/time hook in Atmosphere: on ApplyEnvironment / weather change → VolumetricFog.ApplyPreset(time, weather, 4f) and fog density × VolumetricFog.BuiltInFogScale while active; WindSystem.SetWeather; GpuVfx.SetWeather(rain/snow, cam, intensity); ScreenSpaceSettings.Wetness and TerrainShaderBinder.SetWetness from rain amount (0.2 dry baseline). Align AtmosphereMath.VolumetricAllowed with VolumetricFog tier table (Orta cheapest ON).`],
  ['I2-dunya-editor', `FILES YOU OWN: Infrastructure/World/** (WorldWater, TerrainGenerator, VegetationMaterials, TreeMeshes/TreeFactory, WorldGenerator), Infrastructure/Rendering/WaterSurface*.cs, Rendering/MaterialLibrary.cs, Editor/** (SceneBuilder.cs, ProjectSetup.cs / BatchEntry, new Editor/AlwaysIncludedShaders.cs).
Wire: PlanarReflection.RegisterAll in WorldWater.Build + PlanarReflection.Install in WaterSurface.Attach; TerrainShaderBinder.Install(terrain, tier from QualitySettings) after terrain.materialTemplate set; MaterialLibrary: wet mud / parallax variants via TerrainShaderBinder.CreateWetMud / CreateParallaxMaterial for ground/mud/rock MaterialIds with ?? fallback; VegetationMaterials: try GrassAssets.TryCreateWindFoliage first; TreeMeshes/TreeFactory: write vertex color R=bend weight (0 at trunk base → 1 at branch tips), G=phase (random per tree/branch), B=AO; Editor: ProjectSetup RunAllSteps add "AAA Benchmark sahnesi" step (AaaBenchmarkSceneBuilder.EnsureScene) + SceneBuilder.EnsureMissingScenes fallback; SceneBuilder after world gen: ReflectionProbePlacer.PlaceFromWorld and HlodBuilder.Build per settlement root (guarded, optional flag default ON); new editor step that adds every shader under Assets/_Project/Shaders (Shader names "HAREKAT/...") to GraphicsSettings Always Included Shaders (via SerializedObject on GraphicsSettings asset, idempotent) and call it from RunAllSteps; make sure URP asset "Strip WriteSmoothness"/prefilter doesn't strip what SSR needs (see S1 note) — if only possible via reflection, do it with a warning fallback.`],
  ['I3-oynanis-kancalari', `FILES YOU OWN: Infrastructure/Vfx/GameVfx*.cs, Infrastructure/Transport/** (Helicopter, FlyableHelicopter, ArmoredCarrier — only hook lines), Infrastructure/Vehicles/** (DrivableVehicle damage hook), Presentation/Bootstrap/** + Presentation/Player/** (spawn hooks only), Infrastructure/Content/ContentOverridesValidator*.cs, Application localization service + Localization JSONs, Tests/EditMode/ViewmodelDynamicsTests.cs (+ the class it tests if the bug is real).
Wire: GameVfx MuzzleFlash/Impact/Explosion/SmokeCloud/RotorWash → GpuVfx.TryPlay first, CPU fallback (keep lights/decals); RotorWash called by Helicopter + FlyableHelicopter + SupportHelicopter when < 15 m above ground (throttled); vehicle condition SetCondition (clean/dirty/burnt) driven by vehicle health + destroyed state; GrassSystem.Install(camera, terrain, tier, waterLevel) at match/skirmish/training/benchmark bootstrap after terrain exists (find the common place) and GrassSystem.AddInteractor for player (0.9) and vehicles (2.5) with RemoveInteractor on despawn; NameProfile.Resolver → LocalizationService and add name.<id> / name.k.<id> keys to tr/en localization JSONs for all weapons/items/vehicles (generate from catalogs); CreditsAudit.AppendTo(sb) at the end of ContentOverridesValidator.Validate adding its errors to HATA count; fix the failing EditMode test ViewmodelDynamicsTests (find which assertion; fix the real bug, not just the test).`],
]
phase('Entegrasyon')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'Entegrasyon', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
