export const meta = {
  name: 'harekat-mapweapon-g16',
  description: 'HAREKÂT G16 harita+silah (ekran görüntüsü kanıtlı): harita doluluk/siper, dağ-kayalık şekillendirme, göl/buz, üçüncü şahıs silah modeli, ping işaretçisi (5 Sonnet ajanı)',
  phases: [{ title: 'G16', detail: '5 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const IMG = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/images/10.png'
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g16_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 URP C# at ${ROOT}. FIRST ACTION: Read the owner's gameplay screenshot ${IMG} with the Read tool (Ayaz Geçidi map, spectator view) — your task fixes defects visible in it. Target: PUBG map readability/density.
Parallel agents own these files, do NOT edit them: Rendering/HorizonVista*, SkyEnvironment, CloudShadows*, AtmosphereDetail*, MaterialLibrary.cs, World/TreeMeshes, TreeFactory, VegetationMaterials, VegetationTextures, World/Grass/**, Presentation/Benchmark/**, Presentation/UI/MenuBackdrop*, MenuCampfire, MenuSceneMath, OtoEkran*. Cross-file needs → "ENTEGRASYON: <file>: <call>" in concerns. Grep APIs first; deterministic by seed; NavMesh-safe props.
Do NOT launch Unity. Verify with ${V(id)} (0 errors in your files; ~1595 tests passing; others' in-flight errors not yours). No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. One dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük".`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['M1-harita-doluluk', 'SCOPE: Infrastructure/World/LocationBuilder.cs, MapLayout*.cs (all 4 maps), WorldGenerator.cs scatter orchestration, new World/MicroPoi*.cs (uses PropFactory/RockScatter/TreeScatter PUBLIC APIs only). DEFECT: open fields are completely EMPTY green hills — no cover for hundreds of meters (screenshot proves it). Fix like PUBG: a deterministic micro-POI pass fills the space BETWEEN settlements so every ~80-120 m cell off-road has something: rock cluster, 2-3 tree copse, bush line, ruined wall corner, shepherd hut (çoban kulübesi), sheep pen, haystack, fallen log, small trench/foxhole with sandbags, abandoned cart; density per map personality (Kuzgun forest-heavy, Ayaz sparse+snowy variants: snowdrift mounds, frozen dead trees, rock cairns), never on roads/water/settlement radius, count budget ~150-250 per km² with LOD-friendly reuse. Guarantee combat usefulness: at least knee-high cover items. Keep generation time +%15 max; NavMesh obstacles registered like existing props.'],
  ['M2-dag-kayalik', 'SCOPE: Infrastructure/World/TerrainGenerator.cs (mountain shaping + splat on steep), TerrainErosion*.cs params, RockScatter.cs (cliff outcrop placement), TerrainPainter slope rules. DEFECT: mountains are smooth white BLOBS — no rock, no ridgeline character (screenshot). Fix: steep slopes (>35°) get rock splat layer + macro darkening; mountain tops: sharper ridges via ridge-noise blended at high altitude, erosion gullies visible; place big rock outcrop clusters on cliffs via RockScatter (ThirdParty boulders if bound); Ayaz snowline: snow only above a height band with rocky patches exposed on steep faces (slope-based snow mask), subtle sparkle handled by material (read-only). Keep layouts/roads flat areas untouched; deterministic; generation +%15 max. Numeric tests for the masks (slope/height thresholds).'],
  ['M3-gol-buz', 'SCOPE: Infrastructure/World/WorldWater.cs, Rendering/WaterSurface*.cs (visual params), new Rendering/IceSurface*.cs. DEFECT: the lake reads as a flat GRAY SMEAR (screenshot). Fix: water color deep blue-green with proper fresnel to sky, visible wave normal animation, shore darkening band; AYAZ map: lakes FROZEN — ice material (procedural: bluish white albedo, crack lines texture, high smoothness low metallic, subtle subsurface tint), walkable (collider already? grep — if water blocks movement keep blocking on ice too unless trivial), scattered snow patches on ice, shore ice rim on other cold conditions optional. Map-based switch via map id / temperature flag (grep MapCatalog for climate info; add a simple IsFrozen flag if missing, default false). NaN-guard meshes.'],
  ['M4-tp-silah', 'SCOPE: Infrastructure/Weapons/WeaponModelFactory.cs (third-person/world model path), Infrastructure/Characters/SoldierModel weapon attach code (grep AttachWeapon/right hand socket), Weapons/WeaponBlueprints scale constants if needed. DEFECT: soldiers hold a thin BLACK STICK — third-person weapon is unreadably small/dark (screenshot). Fix: (1) ensure ContentOverrides WeaponOverride prefabs (Quaternius models were bound by ThirdPartyWeaponBinder — grep its output contract) are ALSO used for the third-person/held model path, not only viewmodel; correct scale on soldier (rifle ~0.95 m, visible at 30 m), grip alignment to hand socket (Grip_R), fallback procedural keeps working; (2) procedural TP fallback materials: use lighter gun gray (readable silhouette) + furniture color blocks; (3) held pose: barrel forward along aim, stock at shoulder (grep carry pose transforms; small offsets ok). Do NOT edit MaterialLibrary.cs (owned); use existing material ids or local materials.'],
  ['M5-ping-isaret', 'SCOPE: Presentation/UI/PingWorldView*.cs + ping marker visuals (grep PingBoard world marker rendering; not Map*/Minimap*). DEFECT: the team/danger ping renders as a BIG RED BALL floating over the world (screenshot center). Replace with PUBG-style marker: small billboard icon (diamond for normal, red triangle-! for danger) 28-36 px screen-constant size with thin vertical beam (1-2 px wide, 8 m tall, soft alpha), distance label under it ("325 m"), fades past expiry, occluded variant at 40% alpha, never scales with world distance (screen-space constant). Colors from UiTheme (colorblind palette). Also check the spectated-player overhead marker if that is the red ball source (grep SpectatorController marker). EditMode tests for pure sizing math.'],
]
phase('G16')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G16', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
