export const meta = {
  name: 'harekat-polish-g19',
  description: 'HAREKÂT G19: donanım 3B önizleme, müzik/UI ses cilası, kariyer paneli, netcode v2, maç giriş sinematiği, derleme/test süpürücü (6 Sonnet ajanı)',
  phases: [{ title: 'G19', detail: '6 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g19_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 URP C# at ${ROOT}, Turkish UI, CoD-modern style. ~19 parallel agents; disjoint scopes; cross-file → "ENTEGRASYON" concern. Other waves own: PlayerWeaponHandler, GameSettings/SettingsService/SettingsPanel, SightAlignment/SightVisuals/CrosshairView, WeaponViewModel/ViewmodelDynamics, Vfx/**, HitFeedback*/DamageNumbers, SoldierLook, BallisticsSystem, BotPerception, GameAudio alloc parts, HudController, road/TreeScatter/AmbientLife/FootprintTrail/MapPreviewArt/Hud zone-airdrop views, UiKit, MainMenuController, MenuBackdrop*. Grep APIs first.
Do NOT launch Unity. Verify: ${V(id)} (0 errors in your files). Tests for pure logic. No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. Dated Turkish line to Docs/DURUM.md.`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['C1-donanim-3b', 'SCOPE: Presentation/UI/Loadout*.cs. DONANIM screen CoD-quality: large 3D weapon preview (real override model via WeaponModelFactory if bound, else procedural) on a dark pedestal with 3-point lighting + slow auto-rotate that pauses on drag-rotate, attachment slots as connected nodes over the weapon (line to mount point), stat bars animate on weapon change (hasar/menzil/seri/kontrol/ADS), attachment compare +/- deltas in green/red, camo swatch row applies live to the preview, weapon name + kalibre + açıklama panel. Keep save/apply flow intact.'],
  ['C3-muzik-ui-ses', 'SCOPE: Infrastructure/Audio/Music/** + new Infrastructure/Audio/UiSounds.cs (+ ENTEGRASYON lines for UI callers). Polish: menu theme mix (sidechain-duck pad under melody, final limiter headroom -1 dB), add subtle UI sound set generated procedurally: hover tick (soft 2 ms click), press (deeper thud), tab switch whoosh, back, error buzz, match-found sting, countdown beeps; expose UiSounds.Play(UiSfx) and list ENTEGRASYON one-liners for UiKit button/tab builders (owned elsewhere). Loudness consistent (-18 LUFS ui). Tests for envelope math.'],
  ['C4-kariyer-panel', 'SCOPE: Presentation/UI/CareerPanel*.cs (+ reads CareerService/MatchStatsService public APIs). Career screen worthy of CoD barracks: rank progress header with insignia, 30 medal grid (tiers bronz/gümüş/altın, locked grayed, progress ring, tooltip with threshold), per-weapon stat table sortable (kill/headshot%/accuracy/longest), per-map stats, match history list with placement sparkline (CareerService.PlacementSparkline), career level + season level side by side. Dark theme via UiKit tokens (read-only use).'],
  ['C5-netcode-v2', 'SCOPE: Assets/_Project/Scripts/Online/** only. Build on W10 scaffolding: integrate prediction/reconciliation into NetworkPlayer under HAREKAT_NETCODE (apply server state, replay pending commands), snapshot interpolation for remote players using the adaptive buffer, server-side hitscan validation using the lag-compensation ring buffer (rewind, validate hit, clamp), RPC for the new throwable codes, join-in-progress state sync (zone phase, alive lists), basic server tick budget metrics. Keep OfflineNetworkSession identical; all pure logic tested.'],
  ['C6-giris-sinematik', 'SCOPE: new Presentation/Bootstrap/MatchIntro.cs + EndScreen victory lineup addition (grep EndScreen/MatchSummary file; if owned, ENTEGRASYON). CoD-style match intro (skippable with Space): 8 s sequence — shot 1: T-70 flyover following the heli with squad inside (use insertion heli transform), shot 2: map vista pan with map name + mode typography slide-in, shot 3: squad lineup close-up with rank/name cards popping per soldier; then hand off to normal insertion camera. One null-safe hook line in MatchBootstrap after insertion setup (allowed). Victory: winning squad lineup pose camera + "ZAFER" typography. Letterbox bars during intro; HUD hidden; all timings eased.'],
  ['C7-supurucu', `SCOPE: cross-cutting FIXER (runs while others work; fix ONLY these named issues in files NOT owned by the running waves — ownership list above): (1) Tests/EditMode/MountainRulesTests.cs Outcrop_Rules failing (Expected 4.5 > 4.6000003): read the rule in TerrainPaintRulesMountain/RockScatter — if the constant drifted, fix the TEST bound to the intended constant (or the rule if the rule is wrong); (2) Infrastructure/Weapons/WeaponModelFactory.cs(~150) error 'GetInstanceID' seen in a build log — grep and fix if still present; (3) run ${V('sweep')} at the END, list every remaining error with file:line and fix those in unowned files; report any error that lives in an owned file as ENTEGRASYON instead of editing. Target: 0 errors, 0 failed tests. Also grep Logs/claude/*.log for new 'Shader error' lines and fix trivial shader syntax (1.0h literals etc.) in Shaders/** — shaders are unowned now.`],
]
phase('G19')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G19', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
