export const meta = {
  name: 'harekat-polish-g12',
  description: 'HAREKÂT G12: G11 oynanış kancaları + AAA HUD + ölüm/izleme deneyimi + AAA ana menü (4 Sonnet ajanı)',
  phases: [{ title: 'G12 Cila', detail: '5 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g12_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR: 10-person timler with TSK ranks, T-70/Kirpi insertion, Turkish weapons), Unity 6000.6.4 URP C# at ${ROOT}, UGUI with LegacyRuntime font, Turkish UI. Owner goal: make the game itself much better, AAA feel (CoD MW / PUBG / Tarkov). Read existing code first (grep) and improve it.
PARALLEL: graphics waves are editing Rendering/**, Shaders/**, Characters/** (materials), Weapons/** (materials), World/BuildingGenerator*, World/Terrain*, World/DecalScatter*, Assets/ThirdParty/**, Editor/ThirdParty/**, Editor/BatchEntry.cs, Presentation/Benchmark/**, Bootstrap arg parsing, Resources/Audio/**. The 4 G12 agents have disjoint scopes per task. Use "ENTEGRASYON: <file>: <call>" in concerns for anything outside your scope.
Do NOT launch Unity. Verify with ${V(id)} (0 errors, all tests passing). EditMode tests for pure logic. No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. Append a dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük".`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['Q1-oynanis-kancalari', `SCOPE: Infrastructure/AI/**, Infrastructure/Combat/BallisticsSystem.cs, Infrastructure/Player/**, Infrastructure/Audio/** (hook lines only), Application/Services/BotDifficultyProfile*, Presentation/Player/PlayerController.cs (hook lines only). Wire every "ENTEGRASYON" line in ${ROOT}/Tools/AgentWorkflows/notes/g11_concerns.txt (bot near-miss event from player shots with the bot Combatant, breathing audio when stamina low, footstep cadence from movement speed, stamina/HUD hooks, loot/zone/airdrop hooks, etc.). Lean pose: if SoldierModel has no lean hook, add a minimal SoldierModel.SetLean(float -1..1) in a NEW partial file Characters/SoldierModel.Lean.cs (do not edit other Characters files) and call it from bot peek logic. Fix concern: BotDifficultyProfile reaction times are overridden — make BotSkill respect difficulty (Easy slower: 0.35–0.9 s) and keep seed determinism documented. Also review the other G11 concerns and fix real issues.`],
  ['Q2-hud', 'SCOPE: Presentation/UI/Hud*.cs, Compass*, Killfeed*, HitMarker*, DamageIndicator*, AmmoCounter* and new Presentation/UI/Hud/*.cs (NOT SettingsPanel, not menus, not Spectator/Death UI). AAA minimal military HUD: compass bar with degrees + cardinal letters (K, D, G, B in Turkish) + squad pings/markers, squad list with rank insignia and health bars (10 timsiz), subtle hit markers (white, red X on kill, headshot variant), directional damage indicators, killfeed (rank + name + weapon icon text), ammo/fire mode readout that fades when idle (Tarkov-like optional "şarjör kontrol" key shows approximate count), stance indicator, stamina bar only when not full, zone timer, grenade warning icon, interaction prompts styled consistently; HUD scale + opacity respect existing settings; colorblind palette (UiTheme). Clean typography, drop shadows, safe area.'],
  ['Q3-olum-izleme', 'SCOPE: Presentation/Player/Spectator*.cs, Presentation/UI/Death*.cs, DownedOverlay*, Revive*, new Presentation/UI/DeathRecap*.cs, KillCam*. Death experience: death recap (killer name + rank, weapon, distance, hit locations, damage taken timeline, killer HP left), short killcam replay from killer view using existing Replay data/recorder if feasible else a 3rd-person orbit around killer, then spectate teammates (cycle with mouse buttons, show their HUD essentials), downed (yaralı) state polish: crawl, bleed-out timer ring, "yardım iste" ping, revive progress with interrupt; squad wipe screen with placement + stats; all Turkish.'],
  ['Q4-ana-menu', 'SCOPE: Presentation/UI/MainMenu*.cs, Presentation/Menu/** or MenuBackdrop* (grep MenuBackdropBuilder), new Presentation/UI/Loadout*.cs. VERY MODERN AAA lobby (CoD MW / Valorant-level): 3D backdrop scene (a tim idling around a T-70 on a helipad at dusk, Kirpi, sandbags, camo nets, slow camera drift, volumetric-ish fog, rim light) from existing procedural builders; large bold Turkish typography, left-side nav (OYNA, TİM, DONANIM, SEZON, TEKRARLAR, AYARLAR, ÇIKIŞ) with animated hover states (slide + accent bar + sound), smooth page transitions (fade/slide 0.15-0.25 s eased), subtle animated background vignettes; use UiKit (Q5) components via reflection-safe lookup if present, else local equivalents; OYNA flow: mode card carousel (BR/Çatışma/Konvoy/Rehine/Poligon with procedural key-art thumbnails) then map select with silhouette art; DONANIM: primary/secondary/attachments/camo with rotating 3D weapon preview + stat bars animating; TİM: rank insignia, role picker, career stats; news ticker; version string bottom-right. Keep MainMenuController.ExtraButtons API working.'],
  ['Q5-menu-sayfalar', 'SCOPE: new Presentation/UI/UiKit*.cs + SettingsPanel.cs (visual restructure only; keep every setting + persistence), SeasonPassPanel.cs, ReplayMenuPanel.cs, CosmeticsPanel*.cs, EndScreen/MatchSummary (grep names). Build UiKit: shared design tokens (palette: koyu antrasit zemin, kum/haki vurgu, kırmızı tehlike; spacing scale; font sizes), PanelBuilder (rounded-corner 9-slice sprite generated procedurally, soft shadow, header strip), ButtonStyle (default/hover/pressed/disabled with 0.1 s transitions + click sound hook), Toggle/Slider/Dropdown restyle helpers, tab bar component, tooltip component, scroll list with fade edges. Then modernize: SettingsPanel into left tab categories (Oyun/Grafik/Ses/Kontroller/Erişilebilirlik) with clean rows + live preview hints; SeasonPassPanel horizontal tier strip with reward cards + claim animation; ReplayMenuPanel card list with date/map/sonuç; CosmeticsPanel grid with rarity glows; match end/summary screen modern stat cards. All Turkish, HUD scale respected, no logic changes.'],
]
phase('G12 Cila')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G12 Cila', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
