export const meta = {
  name: 'harekat-systems-9',
  description: 'HAREKÂT dalga 9: tekrar sistemi, uçurulabilir T-70, ATAK desteği, Kartal Yaylası haritası, sezon kartı, yıkılabilirlik, poligon görevleri, nişan yardımı (8 Sonnet ajanı)',
  phases: [{ title: 'Dalga 9', detail: '8 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${ROOT}/Tools/UnityVerify/out_${n} --player --tests`
const RULES = `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6 C# at ${ROOT}. Editor can't run here; verify with ${V('<name>')} — keep 0 errors, all tests passing (737).
Read ${ROOT}/ARCHITECTURE.md sections you need. TOKEN-EFFICIENT: open only needed files (grep). Prefer NEW files in your scope; small null-safe edits elsewhere.
No deletes/.meta/file-changing git. UnityEngine.Application inside Project.* namespaces. Turkish UI. Procedural content. Add EditMode tests for pure logic
(tests that need Infrastructure/Presentation must be wrapped in #if UNITY_EDITOR). Cursor may concurrently fix real-Unity errors anywhere; 7 other Claude agents run in parallel —
stay strictly in your scope.  Append a dated line to ${ROOT}/Docs/DURUM.md "Günlük" when done.`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const F = [
  ['tekrar', `Match replay system: Infrastructure/Replay/ReplayRecorder.cs records at 10 Hz all combatants' position/yaw/pitch/stance/weapon/alive + events (shots, hits, deaths, explosions, zone state) into a compact binary file under Application.persistentDataPath/Replays (UnityEngine.Application); Presentation/Replay/ReplayViewer.cs + new scene-less mode: load replay in the same map scene, spawn lightweight ghost SoldierModels, free-fly camera + follow-player camera, timeline scrubber (play/pause/speed 0.25–4x), kill markers on timeline. Main menu entry "TEKRARLAR" via MainMenuController.ExtraButtons registration (do not edit MainMenuController). One-line start hook in MatchBootstrap. Pure binary format reader/writer in Application with tests.`],
  ['heli-pilot', `Flyable T-70 for players: Infrastructure/Transport/FlyableHelicopter.cs (new) — arcade-realistic flight (collective W/S, yaw A/D, pitch/roll with mouse, auto-hover assist toggle, ground effect, rotor spin-up, landing gear contact, crash damage on hard impact/rotor strike), 1 pilot + 9 passengers (reuse seat logic), door gunners 2 seats with PMT-76 (reuse turret logic from Vehicles). Spawn 1–2 at İleri Üs helipads in BR (VehicleSpawnData near helipads; small hook in MatchBootstrap spawn routine). Player enter/exit via existing interaction path (small PlayerController hook). Sounds/dust reuse. Do not break existing insertion Helicopter.`],
  ['atak', `Support ability "T-129 ATAK Desteği": team commander unlocks after team gets 8 kills (or 300 s cooldown), key H? NO — choose a free key from Application/Services/ControlScheme reserved list (e.g. Key.J is boost… check) — add InputBindings action "AttackHeli" default free key, document in Docs/KONTROLLER.md. A procedural attack helicopter flies in, orbits the marked area for 25 s, fires 20 mm cannon bursts (BallisticsSystem) and 2 rocket salvos (ExplosionSystem) at enemies it can see, can be shot down (HP 1500). AI commanders use it too. New files Infrastructure/Support/*, Application/Services/SupportAbilityService.cs (pure, tests), small hook in Presentation/Player/SquadCommandInput.cs and HUD notification.`],
  ['harita4', `Fourth map "Kartal Yaylası" (high plateau): wide grasslands, yörük tents camp, wind turbine field (rotating blades), stone sheepfolds, small airstrip with hangar, cliff edges, pine forest band, two villages. Follow exactly how Ayaz Geçidi / Mavi Liman were added (read MapLayoutAyazGecidi.cs, MapCatalog, SceneNames, Editor/SceneBuilder, MapGradeTable in Core for grading: golden-green). New MapLayoutKartalYaylasi.cs + wind turbine prop in PropFactory (append) + menu/map selection entries + build settings.`],
  ['sezon-karti', `Season pass (cosmetic only): Design/Progression/season1.json → Resources; Application/Services/SeasonPassService.cs (pure: tiers 1–50, XP per match from MatchResult, free + premium-placeholder tracks, rewards = cosmetics ids from cosmetics.json, persistence via ISettingsStore, tests); Presentation/UI/SeasonPassPanel.cs (horizontal tier track with rewards, current tier, XP bar, claim buttons) registered via MainMenuController.ExtraButtons ("SEZON"); grant rewards into CosmeticsService. No real-money flow — premium track shows "yakında".`],
  ['yikim', `Destructibility: window glass panes in BuildingGenerator (thin box, Glass material, breaks into shards on bullet/explosion hit with sound + VFX, removes collider), wooden fences/crates/doors (PropFactory pieces get a Destructible component with HP; explosions/vehicles/many bullets break them into debris chunks that fade), Kirpi/Cobra ramming breaks fences. New Infrastructure/Combat/Destructible.cs + small hooks in BallisticsSystem hit path and ExplosionSystem; keep NavMesh sane (destructibles marked as NavMeshObstacle carve=false or excluded from bake). Pool debris.`],
  ['poligon-gorev', `Training range challenges (beyond tutorial): Presentation/Training/ChallengeController.cs + Application/Services/ChallengeRules.cs (pure, tests): "Hızlı Atış" (pop-up targets at 25–100 m, 60 s, score), "Keskin Nişancı" (200/300/500 m targets with JNG-90, wind-free, hit count), "Kill House" (timed CQB through the 2 buildings with friendly/enemy cutouts, penalty for friendlies), "Bomba Atma" (land frags in rings). Local high scores via ISettingsStore, results screen, start pads in TrainingRangeBuilder (append pads only), menu inside training via E at pad.`],
  ['erisim', `Gamepad aim assist + accessibility: aim assist (slowdown near enemy hitboxes + light magnetism when ADS, only for gamepad input, strength setting 0–100, disabled for mouse), subtitle size/background setting for radio subtitles, colorblind palettes applied to ally/enemy markers & hitmarkers (UiTheme already has a mode — wire everywhere markers are drawn), HUD scale applied to all HUD roots, toggle-ADS / toggle-crouch options. Scope: Presentation/Player/PlayerWeaponHandler (aim assist hook only), new Presentation/Player/AimAssist.cs, SettingsPanel, GameSettings/SettingsService, UiTheme consumers.`],
]
phase('Dalga 9')
const out = await parallel(F.map(([k, task]) => () => agent(`${RULES}\nTASK ${k}: ${task}`, { label: k, phase: 'Dalga 9', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
