export const meta = {
  name: 'harekat-visual-8',
  description: 'HAREKÂT dalga 8: AAA görsel kalite (URP ışık/post, doku kalitesi, VFX, kamera hissi) + Türkçe seslendirme (5 Sonnet ajanı)',
  phases: [{ title: 'Dalga 8', detail: '5 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${ROOT}/Tools/UnityVerify/out_${n} --player --tests`
const RULES = `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6 C# at ${ROOT}. Editor can't run here; verify with ${V('<name>')} — keep 0 errors, all tests passing (502).
Read ${ROOT}/ARCHITECTURE.md sections you need. TOKEN-EFFICIENT: open only needed files (grep). Prefer NEW files in your scope; small null-safe edits elsewhere.
No deletes/.meta/file-changing git. UnityEngine.Application inside Project.* namespaces. Turkish UI. Procedural content. Add EditMode tests for pure logic
(tests that need Infrastructure/Presentation must be wrapped in #if UNITY_EDITOR). Cursor is concurrently fixing real-Unity errors anywhere; 10 other Claude agents run in parallel (wave 7 owns: WeaponCatalog/WeaponModelFactory/ItemCatalog/LootSpawnService, Infrastructure/Vehicles/*, Rendering/NightVision*, InputBindings, PlayerController, BotPerception, Convoy*/Hostage* bootstraps, Tests) —
stay strictly in your scope.  Append a dated line to ${ROOT}/Docs/DURUM.md "Günlük" when done.`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const F = [
  ['grafik-urp', `Goal: Call-of-Duty/PUBG-like image quality from the renderer. Scope Infrastructure/Rendering/* (except NightVision*), Editor/AssetGeneration.cs, Editor/SceneBuilder.cs (lighting parts only). URP: per quality tier enable SSAO renderer feature, Decal renderer feature (for bullet holes/blood if Vfx supports URP decals), HDR, soft shadows with 4 cascades on High/Ultra, shadow resolution tiers, SMAA/TAA option, render scale. Post: ACES tonemapping, tuned color grading per map (Kuzgun warm-olive, Ayaz cold-blue, Mavi Liman bright-teal) via ColorAdjustments/ShadowsMidtonesHighlights/WhiteBalance, subtle chromatic aberration + film grain + lens vignette, Depth of Field during ADS (gaussian, near blur) and on death cam, motion blur option (settings). Lighting: SceneBuilder adds reflection probes (village/base centers), light probe groups near buildings, ambient from gradient/skybox, realistic sun intensity/color temperature, fog density per map; procedural skybox tuned. Add URP stub members if needed in Tools/UnityVerify/stubs (signatures from the URP 17.6 sources under /Applications/Unity/Hub/Editor/6000.6.0f1 is gone — use real package source in Library/PackageCache if present, else BuiltInPackages of the installed 6000.6.4f1 editor) and rebuild stubs with setup_deps.sh.`],
  ['doku-kalite', `Scope Infrastructure/Rendering/ProceduralTextures*.cs, MaterialLibrary*.cs, MaterialSpec*.cs, Infrastructure/World/TerrainTextureFactory.cs. Higher-fidelity procedural PBR: 1024px tileable albedo with multi-octave detail, generated NORMAL maps (from height via Sobel) and mask maps (metallic/AO/smoothness) for stone, plaster, brick, wood, metal, concrete, camo fabric, gun metal/polymer, terrain layers (grass/dirt/rock/snow/gravel/mud/sand) with normal maps on TerrainLayer; URP Lit keywords _NORMALMAP/_MASKMAP set correctly; cache textures; keep runtime generation time reasonable (generate lazily, or at editor time via AssetGeneration which already persists).`],
  ['vfx-kalite', `Scope Infrastructure/Vfx/*. AAA-style effects within procedural limits: muzzle flash (multi-quad star + core + smoke puff + 1-frame light, per weapon class, suppressed variant), shell ejection (pooled physical casings with tinkle), impacts per surface (dust/debris chunks/sparks/wood splinters/snow puff/water splash) with sub-emitters, bullet hole decals with normal-ish darkening and per-surface variants, blood mist + ground decals, explosion (fireball, shockwave ring, debris, lingering smoke column, scorch decal, camera dust), heavier smoke grenade volume, rotor-wash dust rings, footstep dust on dirt/snow. Respect pool caps and quality tier (lower counts on Low).`],
  ['kamera-his', `Scope Infrastructure/Player/FirstPersonCameraController.cs, Infrastructure/Player/CharacterControllerMotor.cs (feel only), Presentation/Player/PlayerCameraFx*.cs (new). CoD-like camera feel: sprint FOV kick (+6°) and head bob curve, slide-to-crouch when crouching from sprint (short momentum slide), mantle/vault over obstacles ≤1.2 m (raycast check, smooth camera arc) — mantle implemented in motor with clean collision, landing camera dip proportional to fall speed, weapon switch camera nudge, ADS FOV ease, explosion & hit shakes with directional bias, subtle idle sway. Settings toggle for camera shake intensity (read from GameSettings if field exists, else add).`],
  ['ses-turkce', `Turkish voice lines. Input ${ROOT}/Design/Audio/telsiz_replikleri.csv (225 lines: anahtar,durum,konusan_rol,metin_tr,...). Generate real Turkish speech with macOS TTS: for each row run say -v Yelda -r 190 -o /tmp-or-scratch/<anahtar>.aiff "<metin_tr>" then afconvert -f WAVE -d LEI16@22050 -c 1 to ${ROOT}/Assets/_Project/Resources/Audio/Voice/<anahtar>.wav (create folder). Write Assets/_Project/Resources/Audio/Voice/voice_manifest.json (key→file, role, durum, text). Then in Infrastructure/Audio/Radio*.cs (existing radio chatter) play the voice clip through a radio-style filter (AudioHighPassFilter ~400 Hz + AudioLowPassFilter ~3.5 kHz + light distortion) with squelch before/after, subtitle unchanged; local player callouts (reload "Şarjör!", grenade "Bomba!", contact, ally down, revive) via the same system with player voice (no radio filter, slight pitch down 0.92 for a deeper tone). Pitch-shift teammates per role (0.85–0.95) to vary voices. Add Docs note: placeholder TTS (Yelda, macOS) — to be replaced by a voice actor; check license before release. Keep total size reasonable (22 kHz mono).`],
]
phase('Dalga 8')
const out = await parallel(F.map(([k, task]) => () => agent(`${RULES}\nTASK ${k}: ${task}`, { label: k, phase: 'Dalga 8', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
