export const meta = {
  name: 'harekat-visualfix-g15',
  description: 'HAREKÂT G15 görsel düzeltme (ekran görüntüsü kanıtlı): ufuk beyaz şerit, silah görünümü, ağaç kalitesi, vitrin kamera çerçeveleme, çim/kalite, bulut artefaktları (6 Sonnet ajanı)',
  phases: [{ title: 'G15 Görsel', detail: '6 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const SHOTS = `${ROOT}/Logs/otoekran/bench`
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g15_${n} --player --tests`
const RULES = (id, shot) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 URP C# at ${ROOT}. FIRST ACTION: Read the screenshot ${SHOTS}/${shot} with the Read tool and study it — your task fixes a defect visible in it. Target look: PUBG/CoD realistic; current frames look toy-like.
You are one of 6 parallel agents with disjoint scopes; stay in YOUR files; cross-file needs → "ENTEGRASYON: <file>: <call>" in concerns. Grep APIs before use. Do NOT launch Unity. Verify with ${V(id)} (0 errors in your files; tests passing ~1595). No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. One dated Turkish line to ${ROOT}/Docs/DURUM.md "Günlük".`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['V1-ufuk-serit', '02_asker.png', 'SCOPE: Infrastructure/Rendering/HorizonVista*.cs, SkyEnvironment.cs (vista parts), AtmosphereMath aerial color if needed. DEFECT: the horizon mountains render as a SOLID WHITE BAND brighter than the sky — looks like a white wall across the screen. Likely causes to check and fix: vista layer color = fog color but fog color is near-white while sky at horizon is blue-gray (mismatch); unlit material without fog blend toward SKY HORIZON color; layers too tall/too close so they cover the sky band; alpha/gradient not applied. Fix: vista silhouettes must be DARKER than the sky at the horizon in daylight (atmospheric scattering: distant ridges ≈ horizon sky color but 5-15% darker, bluer; nearer layer slightly darker/greener), correct height so ridgeline is irregular (not flat), smooth alpha fade at the top edge, never exceed sky luminance. Validate colors numerically in tests (far layer luminance < horizon sky luminance).'],
  ['V2-silah-gorunum', '01_silah_yakin_plan.png', 'SCOPE: Infrastructure/Rendering/MaterialLibrary.cs (GunMetal/metal entries + viewmodel ambient), Infrastructure/Weapons/WeaponMaterials/materials usage in WeaponBlueprints* (material params only, not meshes), Shaders/Weapon/* if present. DEFECT: the viewmodel gun is a huge pitch-black mass covered in heavy NOISE/SPECKLE (looks like black gravel). Fixes: (1) find the noise source — likely a detail/micro normal or procedural grain texture tiled far too densely on GunMetal (grep ProceduralPbr/gun noise) — reduce tiling ~10x and strength to subtle; (2) GunMetal: albedo ~0.5 gray, metallic 0.9, smoothness 0.55-0.7 so it catches sky reflection; ensure reflection probes/ambient reach the viewmodel layer (check CameraRig overlay camera: if ambient/probe is black for the overlay layer, add a cheap ReflectionProbe or set RenderSettings ambient usage — grep GX4 work: a viewmodel probe may exist but not be wired); (3) expose a single ViewmodelLighting.Install(camera) if needed and list ENTEGRASYON. Also check the weapon fills too much screen: viewmodel position/scale constants (WeaponViewModel hip position) — pull the gun slightly down-right and smaller (~10%).'],
  ['V3-agac-kalite', '02_asker.png', 'SCOPE: Infrastructure/World/TreeMeshes.cs, TreeFactory.cs, VegetationMaterials.cs, VegetationTextures.cs (+ TreeScatter prototype selection). DEFECT: trees are dark low-poly blobs (flat dark-green lumps on sticks, Minecraft-like). The improved LOD card trees exist but either are not used by the terrain tree prototypes or look bad: (1) ensure terrain trees + benchmark forest use the HIGH-DETAIL card-based pine/oak (LOD0) with alpha-cutout leaf textures, not the old blob meshes; (2) leaf color: desaturated olive-green with sun translucency, NOT near-black green; brighten shaded side via vertex AO not pure black; (3) canopy silhouette irregular (randomized card rotations/sizes); trunk with bark texture from ThirdParty if bound (grep VegetationOverride binding — Poly Haven pine prefabs may exist: ThirdPartyModelBinder bound pine/bush/grass — ensure TreeScatter actually PREFERS the override prefabs and they are used as terrain tree prototypes); (4) check why override pines were not visible: BatchEntry.BindThirdParty may never run during SetupAll — if so, add the call into ProjectSetup.RunAllSteps (Editor scope allowed for this one line).'],
  ['V4-vitrin-kamera', '02_asker.png', 'SCOPE: Presentation/Benchmark/** (AaaBenchmark*, Vitrin shot list), Presentation/Bootstrap/OtoEkranRunner.cs framing only. DEFECT: the "02_asker" showcase shot frames empty terrain — no soldier in view; other shots also frame subjects poorly (gun shot is terrain + giant gun). Fix the Vitrin shots to be portfolio-quality: each shot must LOOK AT its subject — compute camera position/rotation from the subject transform at capture time (soldier: 3/4 view at 2.2 m, eye height 1.5 m, subject centered rule-of-thirds; weapon close-up: over-the-shoulder ADS-like angle on the gun; Kirpi: low 15° front-quarter at 6 m; house interior: doorway looking in with window light; forest: inside treeline looking along path; firing: behind shooter while bot fires at targets with tracers). Verify subjects exist before shooting; if missing, spawn them (benchmark scene has soldier/Kirpi/targets — grep). Add a 0.5 s settle and ensure quality tier = Ultra for the 6 main shots (tier shots separate).'],
  ['V5-cim-kalite', '06_hedeflere_ates.png', 'SCOPE: Infrastructure/World/Grass/GrassSystem.cs + GrassAssets.cs (visual params), Presentation/Benchmark feature-install for grass only if a hook is missing (one line). DEFECT: ground is flat green — GPU grass not visible in benchmark captures. Causes to check: GrassSystem.Install not called in benchmark (grep AaaBenchmarkBootstrap/InstallFeatures + BootstrapUtility.InstallGrass), shader missing → silent off (log?), tier too low during capture, density/draw distance too small to read at camera distance, blade size too small, color too close to terrain. Fix: ensure install on benchmark, blades readable at 5-30 m (height 0.25-0.45 m clumps, slight color variation lighter than terrain so it reads), draw distance ≥ 60 m at Yüksek, density per tier; if the HAREKAT/VegetationWind shader failed to compile in build, make fallback use URP/Lit cutout cards with MPB colors (visible even without custom shader) and log one warning. Also write a tiny debug: GrassSystem.Report() string (cells, instances drawn) callable from OtoEkran perf csv (ENTEGRASYON line).'],
  ['V6-bulut-artefakt', '01_silah_yakin_plan.png', 'SCOPE: Infrastructure/Rendering/SkyEnvironment.cs (cloud/cirrus parts only), Rendering/CloudShadows*.cs params, AtmosphereDetail*.cs. DEFECT: thin streak/scratch-like line artifacts across the sky (upper right of the screenshot) — likely the cirrus layer quads/high-altitude streaks or lens-flare occlusion lines rendering as harsh thin lines; also cumulus clouds are blotchy posterized blobs. Fix: cirrus = soft wide wisps (low alpha 0.15-0.3, feathered texture, no hard edges), remove any line-like primitives; cumulus texture: increase octaves/soften thresholds to avoid posterization rings, brighter sunlit tops + slightly gray bottoms; cloud dome seam check. Keep perf: texture generated once. Numeric tests for alpha bounds.'],
]
phase('G15 Görsel')
const out = await parallel(T.map(([id, shot, task]) => () => agent(`${RULES(id, shot)}\nTASK ${id}: ${task}`, { label: id, phase: 'G15 Görsel', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
