export const meta = {
  name: 'harekat-world-g18',
  description: 'HAREKÂT G18 dünya canlılığı: yol ağı v2, orman desenleri, ortam canlılığı (kuş/duman/rüzgâr dalgası), kar ayak izleri, harita seçim önizlemeleri, HUD zamanlayıcı cilası (6 Sonnet ajanı)',
  phases: [{ title: 'G18', detail: '6 paralel ajan' }],
}
const ROOT = '/Users/f2gomac/Desktop/FPS-GAME'
const SCRATCH = '/private/tmp/claude-501/-Users-f2gomac-Desktop-FPS-GAME/68731bbb-b09c-4658-bc93-146394d39180/scratchpad'
const V = (n) => `zsh ${ROOT}/Tools/UnityVerify/verify.sh ${SCRATCH}/v_g18_${n} --player --tests`
const RULES = (id) => `Project HAREKÂT (Turkish-military FPP squad BR), Unity 6000.6.4 URP C# at ${ROOT}, Turkish UI. PUBG-level world liveliness. ~20 parallel agents; disjoint scopes; cross-file → "ENTEGRASYON" concern. Other waves own: LocationBuilder, MapLayout*, TerrainGenerator/Erosion, RockScatter, TerrainPainter, WorldWater/WaterSurface/Ice, WeaponModelFactory, SoldierModel*, SoldierLook, PingWorldView, UiKit, MainMenuController, PlayerWeaponHandler, WeaponViewModel, ViewmodelDynamics, Vfx muzzle/shell files, BallisticsSystem, BotPerception, GameAudio, HudController, HitFeedback*, CrosshairView, SettingsPanel, Loadout*, CareerPanel, Online/**, Audio/Music. Grep first; deterministic by seed; NavMesh-safe.
Do NOT launch Unity. Verify: ${V(id)} (0 errors in your files). Tests for pure logic. No deletes/.meta/file-changing git. UnityEngine.Application inside Project.*. Dated Turkish line to Docs/DURUM.md.`
const SCHEMA = { type: 'object', properties: { summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, concerns: { type: 'array', items: { type: 'string' } } }, required: ['summary', 'files', 'concerns'] }
const T = [
  ['B1-yol-v2', 'SCOPE: Infrastructure/World road code (grep RoadBuilder/RoadMesh/road painting — identify exact files; do NOT edit TerrainPainter/TerrainGenerator, use their public APIs). PUBG-readable roads: smooth curved centerlines (Catmull-Rom through layout waypoints), proper width hierarchy (ana yol 7 m asfalt-çakıl, köy yolu 4.5 m toprak), banked edges blending into grass, roadside details: km taşları, wooden power poles with sagging wire along main roads (prop budget), occasional guardrail on slopes, tire ruts center strip; junctions blended (no hard overlaps). Deterministic; respects bridges/water (grep).'],
  ['B2-orman-desen', 'SCOPE: Infrastructure/World/TreeScatter.cs (+ its rules). Natural forest composition: clustered stands with clearings (Poisson/noise mask, not uniform), dense treeline edges along fields/roads (PUBG tree lines for cover), mixed species per biome (pine ridges, oak valleys), undergrowth bushes concentrated at forest edges, fallen logs inside forests (prop id via override/PropFactory ENTEGRASYON if needed), density budget per km² unchanged ±%10. Deterministic; tests for mask math.'],
  ['B3-ortam-canlilik', 'SCOPE: new Infrastructure/World/AmbientLife*.cs (+ small WindSystem API read). Living world: distant bird flocks (5-9 billboard birds, flock path loops over valleys, scatter on nearby gunfire via Acoustics event if public), chimney smoke columns from village houses at dawn/dusk/cold maps, wind gust waves rolling across grass/trees (drive WindSystem gust parameter in slow moving bands), butterflies/insects near flowers at noon (tiny billboards, near camera only), crickets layer hook at night (ENTEGRASYON Audio). All tier-limited, pooled, deterministic-ish; auto-installed per map via one bootstrap hook (null-safe one line in MatchBootstrap allowed).'],
  ['B4-kar-iz', 'SCOPE: new Infrastructure/Vfx/FootprintTrail.cs (+ uses DecalPool public API). Snow/mud footprints: player+bots leave alternating boot decals on Snow and Mud SurfaceKind (grep FootstepEmitter surface detection — subscribe or small hook line ENTEGRASYON), fade after 60 s, pooled 256 cap, vehicles leave tire track segments on snow/mud (hook DrivableVehicle wheel positions via public API or ENTEGRASYON), tier-limited. Tests for spacing/pool rules.'],
  ['D2-harita-onizleme', 'SCOPE: new Presentation/UI/MapPreviewArt.cs (+ data read from MapLayout/minimap texture pipeline public APIs). Generate per-map top-down preview images at runtime once (cacheable to persistentDataPath): stylized PUBG-style map art — terrain heights shaded, forests dark green patches, roads cream lines, settlements named dots, water blue, border frame + map name typography. Expose MapPreviewArt.Get(mapId) Texture2D for the mode/map select cards and loading screen (ENTEGRASYON lines for MainMenuController/LoadingScreen owners).'],
  ['D3-hud-sayac', 'SCOPE: Presentation/UI/Hud/ zone/airdrop timer views (grep; not HudController core — add views it already ticks or self-install). Polish: zone countdown with radial wipe + color shift white→amber→red, "BÖLGE KAPANIYOR" slide-in banner 2 s, airdrop inbound banner with parachute glyph + direction arrow, phase transition stingers hook (ENTEGRASYON Audio), all animations 0.15-0.25 s eased, respects HUD scale/opacity.'],
]
phase('G18')
const out = await parallel(T.map(([id, task]) => () => agent(`${RULES(id)}\nTASK ${id}: ${task}`, { label: id, phase: 'G18', schema: SCHEMA, model: 'sonnet', effort: 'medium' })))
return out.filter(Boolean)
