#!/usr/bin/env python3
"""
HAREKAT - Steam basarim esleme ureteci.

Kaynak : Design/Progression/achievements.json  (backend AchievementCatalog id'leri ile ayni)
Ciktilar:
  Assets/_Project/Scripts/Platform/SteamAchievementMap.cs            (backend id -> Steam API adi)
  Assets/_Project/Scripts/Platform/Steamworks~/achievements_partner.csv (Partner'a girilecek liste)

Kullanim (depo kokunden):
  python3 "Assets/_Project/Scripts/Platform/Steamworks~/tools/gen_steam_achievements.py"
Windows:
  py "Assets\\_Project\\Scripts\\Platform\\Steamworks~\\tools\\gen_steam_achievements.py"

Steam API adi kurali: "ACH_" + id.upper() (harf/rakam disi karakterler "_" olur).
Ayni kural SteamAchievementMap.ToConventionApiName icinde de uygulanir; listeye girmemis yeni
backend id'leri de bu kuralla eslenir.
"""
import csv
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PLATFORM = os.path.normpath(os.path.join(HERE, "..", ".."))
ROOT = os.path.normpath(os.path.join(PLATFORM, "..", "..", "..", ".."))
SOURCE = os.path.join(ROOT, "Design", "Progression", "achievements.json")
OUT_CS = os.path.join(PLATFORM, "SteamAchievementMap.cs")
OUT_CSV = os.path.join(PLATFORM, "Steamworks~", "achievements_partner.csv")


def api_name(backend_id: str) -> str:
    return "ACH_" + re.sub(r"[^A-Za-z0-9]", "_", backend_id).upper()


def cs_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    with open(SOURCE, encoding="utf-8") as f:
        data = json.load(f)
    items = data["achievements"]
    ids = [a["id"] for a in items]
    if len(ids) != len(set(ids)):
        print("HATA: achievements.json icinde tekrar eden id var", file=sys.stderr)
        return 1

    lines = []
    for a in items:
        lines.append(f"            {{ {cs_string(a['id'])}, {cs_string(api_name(a['id']))} }}, // {a.get('category', '')}: {a['title']}")
    if lines:
        lines[-1] = lines[-1].replace("}, //", "} //", 1)

    cs = f'''// <auto-generated>
// Bu dosya Steamworks~/tools/gen_steam_achievements.py tarafindan
// Design/Progression/achievements.json ({len(items)} basarim) kaynagindan uretildi. Elle duzenlemeyin; ureteci calistirin.
// </auto-generated>
using System;
using System.Collections.Generic;

namespace Project.Platform
{{
    /// <summary>
    /// Backend basarim id'leri (<c>Harekat.Domain.Catalogs.AchievementCatalog</c> = Design/Progression/achievements.json)
    /// ile Steamworks API adlari arasinda esleme. Steam Partner'da ayni API adlariyla basarim tanimlari olusturulmalidir
    /// (liste: <c>Steamworks~/achievements_partner.csv</c>).
    /// </summary>
    public static class SteamAchievementMap
    {{
        /// <summary>Esleme kaynagi.</summary>
        public const string Source = "Design/Progression/achievements.json";

        /// <summary>Kaynaktaki basarim sayisi.</summary>
        public const int Count = {len(items)};

        /// <summary>Steam API adi on eki.</summary>
        public const string ApiNamePrefix = "ACH_";

        static readonly Dictionary<string, string> BackendToSteam = new Dictionary<string, string>(StringComparer.Ordinal)
        {{
{chr(10).join(lines)}
        }};

        static Dictionary<string, string> _steamToBackend;

        /// <summary>Tum acik eslemeler (backend id -> Steam API adi).</summary>
        public static IReadOnlyDictionary<string, string> All => BackendToSteam;

        /// <summary>Id acik listede mi (Partner'da tanimli olmasi beklenen basarimlar).</summary>
        public static bool IsKnown(string backendAchievementId)
        {{
            return !string.IsNullOrWhiteSpace(backendAchievementId) && BackendToSteam.ContainsKey(backendAchievementId);
        }}

        /// <summary>Acik listede olan id icin Steam API adi.</summary>
        public static bool TryGetSteamApiName(string backendAchievementId, out string steamApiName)
        {{
            return TryGetSteamApiName(backendAchievementId, false, out steamApiName);
        }}

        /// <summary>
        /// Steam API adi. <paramref name="allowConvention"/> true ise listede olmayan yeni backend id'leri
        /// <see cref="ToConventionApiName"/> kuraliyla eslenir (Partner'da tanimli degilse Steam reddeder; zararsiz).
        /// </summary>
        public static bool TryGetSteamApiName(string backendAchievementId, bool allowConvention, out string steamApiName)
        {{
            steamApiName = null;
            if (string.IsNullOrWhiteSpace(backendAchievementId))
                return false;

            var id = backendAchievementId.Trim();
            if (BackendToSteam.TryGetValue(id, out steamApiName))
                return true;

            if (!allowConvention)
                return false;

            steamApiName = ToConventionApiName(id);
            return steamApiName != null;
        }}

        /// <summary>Steam API adindan backend id'si (yalnizca acik liste).</summary>
        public static bool TryGetBackendId(string steamApiName, out string backendId)
        {{
            backendId = null;
            if (string.IsNullOrWhiteSpace(steamApiName))
                return false;

            if (_steamToBackend == null)
            {{
                var reverse = new Dictionary<string, string>(StringComparer.Ordinal);
                foreach (var pair in BackendToSteam)
                    reverse[pair.Value] = pair.Key;
                _steamToBackend = reverse;
            }}

            return _steamToBackend.TryGetValue(steamApiName.Trim(), out backendId);
        }}

        /// <summary>Kural: <c>"ACH_" + id.ToUpperInvariant()</c>; harf/rakam disi karakterler alt cizgi olur.</summary>
        public static string ToConventionApiName(string backendAchievementId)
        {{
            if (string.IsNullOrWhiteSpace(backendAchievementId))
                return null;

            var id = backendAchievementId.Trim();
            var chars = new char[id.Length];
            for (var i = 0; i < id.Length; i++)
            {{
                var c = id[i];
                var ascii = c < 128 && char.IsLetterOrDigit(c);
                chars[i] = ascii ? char.ToUpperInvariant(c) : '_';
            }}

            return ApiNamePrefix + new string(chars);
        }}
    }}
}}
'''
    with open(OUT_CS, "w", encoding="utf-8", newline="\n") as f:
        f.write(cs)

    os.makedirs(os.path.dirname(OUT_CSV), exist_ok=True)
    with open(OUT_CSV, "w", encoding="utf-8-sig", newline="") as f:
        w = csv.writer(f)
        w.writerow([
            "api_name", "backend_id", "category",
            "display_name_turkish", "description_turkish",
            "display_name_english", "description_english",
            "hidden", "metric", "target", "icon_idea",
        ])
        for a in items:
            w.writerow([
                api_name(a["id"]), a["id"], a.get("category", ""),
                a.get("title", ""), a.get("description", ""),
                a.get("titleEn", ""), a.get("descriptionEn", ""),
                0, a.get("metric", ""), a.get("target", ""), a.get("iconIdea", ""),
            ])

    print(f"{len(items)} basarim -> {os.path.relpath(OUT_CS, ROOT)}, {os.path.relpath(OUT_CSV, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
